#!/bin/bash

#delete existing bucket
/opt/couchbase/bin/couchbase-cli bucket-delete -c 127.0.0.1:8091 --bucket=default -u Administrator -p password

#add second node
/opt/couchbase/bin/couchbase-cli rebalance -c 127.0.0.1:8091 --server-add={serverip} --server-add-username=Administrator --server-add-password=password -u Administrator -p password
