#!/usr/bin/env python

import sys
import unittest
import os
sys.path.append("lib")
sys.path.append("pytests")

from memcachedops.fill_bucket import FillTheBucketTest

if __name__ == '__main__':
    os.environ["SERVERS"] = "10.1.5.192:8091:11211:11210 10.1.5.193:8091:11211:11210"
    suite = unittest.TestLoader().loadTestsFromTestCase(FillTheBucketTest)
    from TestInput import TestInputParser,TestInputSingleton
    TestInputSingleton.input = TestInputParser.get_test_input(sys.argv)
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    if len(result.failures) > 0 or len(result.errors) > 0:
        sys.exit(-1)
    sys.exit(0)
