#!/usr/bin/env python

import sys
import unittest
sys.path.append("lib")
sys.path.append("pytests")

from management.add_rebalance import AddRebalanceNodesTest

if __name__ == '__main__':
    suite = unittest.TestLoader().loadTestsFromTestCase(AddRebalanceNodesTest)
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    if result.failures or result.errors:
        sys.exit(-1)
    sys.exit(0)
