ent_backup_restore.enterprise_backup_restore_test.EnterpriseBackupRestoreTest:
    test_backup_without_objstore_bucket,objstore_provider=s3,GROUP=P1,items=100000
    test_config_without_objstore_bucket,objstore_provider=s3,GROUP=P1,items=100000
    test_info_without_objstore_bucket,objstore_provider=s3,GROUP=P1,items=100000
    test_objstore_negative_args,objstore_provider=s3,GROUP=P0,items=100000
    test_remove_without_objstore_bucket,objstore_provider=s3,GROUP=P1,items=100000
    test_restore_start_after_end,objstore_provider=s3,should-fail=true,items=100000
    test_restore_without_objstore_bucket,objstore_provider=s3,GROUP=P1,items=100000
