ent_backup_restore.enterprise_backup_restore_test.EnterpriseBackupRestoreTest:
    test_backup_with_purge_interval_set_to_float,nodes_init=2,same-cluster=True,GROUP=P0,items=100000
    test_backup_restore_with_rebalance,items=100000,nodes_init=2,nodes_in=1,nodes_out=1,same-cluster=True,skip_consistency=True,per_node=False,force-updates=True,GROUP=P0
    test_backup_restore_with_rebalance,items=100000,nodes_init=2,nodes_in=0,nodes_out=1,same-cluster=True,skip_consistency=True,per_node=False,force-updates=True,GROUP=P1
    test_backup_restore_with_rebalance,items=100000,nodes_init=2,nodes_in=1,nodes_out=0,same-cluster=True,skip_consistency=True,per_node=False,force-updates=True,GROUP=P1
