ent_backup_restore.backup_service_test.BackupServiceTest:
    test_next_scheduled_time,items=100000
    test_next_scheduled_time,objstore_provider=s3,items=100000
    test_complex_schedule,items=100000
    test_complex_schedule,objstore_provider=s3,items=100000
    test_tasks_scheduled_for_same_time,items=100000
    test_tasks_scheduled_for_same_time,objstore_provider=s3,items=100000
    test_merge_options,items=100000
    test_concurrent_merge,items=100000
    test_multiple_repository_schedules,items=100000
    test_multiple_repository_schedules,objstore_provider=s3,items=100000
    test_concurrent_repository_schedules,items=100000
    test_concurrent_repository_schedules,objstore_provider=s3,items=100000
    test_task_queue_overpopulation,items=100000
    test_scheduled_merge,items=100000
    test_scheduled_merge,offset=True,items=100000
