ent_backup_restore.backup_service_test.BackupServiceTest:
    test_shared_directory,lose_shared=some,items=100000
    test_shared_directory,lose_shared=all,items=100000
    test_shared_directory,permissions=ro,items=100000
    test_shared_directory,permissions=wo,items=100000
    test_shared_directory,leader_case=True,items=100000
    test_privileges_revoked_later,case=ro,items=100000
    test_privileges_revoked_later,case=unmount,items=100000
