ent_backup_restore.enterprise_backup_restore_test.EnterpriseBackupRestoreTest:
    test_backup_restore_after_rebalance,items=100000,nodes_init=2,nodes_in=1,nodes_out=1,same-cluster=True,skip_consistency=True,per_node=False,force-updates=True,GROUP=P0
    test_backup_restore_after_rebalance,items=100000,nodes_init=2,nodes_in=0,nodes_out=1,same-cluster=True,skip_consistency=True,per_node=False,force-updates=True,GROUP=P1
    test_backup_restore_after_rebalance,items=100000,nodes_init=2,nodes_in=1,nodes_out=0,same-cluster=True,skip_consistency=True,per_node=False,force-updates=True,GROUP=P1
    test_backup_restore_with_nodes_reshuffle,items=100000,nodes_init=2,same-cluster=True,GROUP=P1
    test_backup_restore_with_nodes_reshuffle,items=100000,nodes_init=2,same-cluster=True,replicas=0,GROUP=P1
    test_backup_and_restore_with_map_buckets,items=100000,map-buckets=true,create-gsi=True,same-cluster=True,dgm_run=True,GROUP=P0
    test_backup_and_restore_with_map_buckets,items=100000,map-buckets=true,create-gsi=True,same-cluster=True,dgm_run=True,delete-old-bucket=True,GROUP=P0
    test_merge_backup_from_old_and_new_bucket,items=100000,same-cluster=True,bucket_delete=True,GROUP=P0
    test_merge_backup_from_old_and_new_bucket,items=100000,same-cluster=True,bucket_flush=True,GROUP=P1
