ent_backup_restore.backup_service_test.BackupServiceTest:
    test_default_plans,first_test=True,items=100000
    test_invalid_plan,items=100000
    test_valid_plan,items=100000
    test_delete_plan,items=100000
    test_delete_plan_tied_to_repository,items=100000
    test_plan_task_limits,items=100000
    test_attach_plan_to_repository,items=100000
    test_large_number_of_plans,items=100000
    test_create_plans_with_same_name,items=100000
    test_deleted_plans_name_can_be_reused,last_test=True,items=100000
    test_creating_plan_simultaneously_on_two_nodes,items=100000
    test_change_plan_for_active_repository,items=100000
