ent_backup_restore.backup_service_test.BackupServiceTest:
    test_restoring_eventing,standard_buckets=3,bucket_storage=couchstore,bucket_size=100,items=100000
    test_restoring_views,bucket_storage=couchstore,items=100000
    test_restoring_indexes,items=100000
    test_restoring_fts,items=100000
    test_restoring_analytics,items=100000
