ent_backup_restore.backup_service_test.BackupServiceTest:
    test_cbbackupmgr_info,items=100000
    test_cbbackupmgr_info,objstore_provider=s3,items=100000
    test_cbbackupmgr_restore,items=100000
    test_cbbackupmgr_restore,objstore_provider=s3,items=100000
    test_rbac_create_repository,items=100000
    test_rbac_other_operations,items=100000
    test_backup_stats,items=100000
    test_minimum_tls_version,items=100000
    test_cluster_ops,cluster_op=rebalance,items=100000
    test_cluster_ops,cluster_op=failover,items=100000
    test_killing_the_backup_service,skiptask=False,items=100000
    test_killing_the_backup_service,skiptask=True,items=100000
    test_orphan_detection,items=100000
