ent_backup_restore.backup_service_test.BackupServiceTest:
    test_restoring_collections,no_of_scopes=5,no_of_collections=5,items=4000
    test_restoring_collections,no_of_scopes=1,no_of_collections=500,items=200
    test_restoring_collections,no_of_scopes=2,no_of_collections=250,items=200
    test_restoring_collections,no_of_scopes=250,no_of_collections=2,items=200
    test_restoring_collections,no_of_scopes=20,no_of_collections=20,items=250
    test_merging_and_restoring_with_collections,no_of_scopes=5,no_of_collections=5,items=4000
    test_merging_and_restoring_with_collections,no_of_scopes=1,no_of_collections=1000,items=100
    test_logs_can_be_collected,items=100000
    test_logs_can_be_redacted,items=100000
    test_logging,items=100000,reset_time=True
    test_logs_for_sensitive_information,objstore_provider=s3,items=100000
    test_audit_service,items=100000
