ent_backup_restore.enterprise_backup_restore_test.EnterpriseBackupRestoreTest:
    test_negative_read_only_archive,read_only_archive=True,items=100000
    test_negative_read_only_archive,read_only_archive=True,compact=True,items=100000
    test_negative_read_only_archive,read_only_archive=True,invalid_auth=True,items=100000
    test_negative_read_only_archive,read_only_archive=True,compact=True,invalid_auth=True,items=100000
