ent_backup_restore.enterprise_backup_restore_test.EnterpriseBackupRestoreTest:
    test_backup_restore_sanity,items=100000,expires=30,GROUP=P0
    test_restore_from_compacted_backup,items=100000,GROUP=P0
    test_backup_restore_sanity,items=100000,non-master=True,nodes_init=2,GROUP=P1
    test_backup_restore_with_lesser_nodes,items=100000,nodes_init=3,GROUP=P0
    test_backup_and_restore_with_map_buckets,standard_buckets=1,items=100000,GROUP=P0
    test_backup_and_restore_with_map_buckets,default_bucket=False,standard_buckets=1,items=100000,map-buckets=true,GROUP=P0
    test_backup_and_restore_with_map_buckets,items=100000,map-buckets=true,GROUP=P0
    test_backup_and_restore_with_map_buckets,items=100000,map-buckets=true,create-gsi=True,GROUP=P0
    test_backup_and_restore_with_map_buckets,default_bucket=False,standard_buckets=3,items=100000,map-buckets=true,dgm_run=True,GROUP=P1
    test_merge_with_crash,items=500000,GROUP=P0
    test_compact_with_crash,items=500000,GROUP=P0
    test_backup_merge,items=100000,number_of_backups=5,GROUP=P1
    test_backup_merge_with_restore,items=100000,GROUP=P0
    test_backup_merge_with_unmerged,items=100000,GROUP=P0
    test_backup_resume,resume=True,items=500000,GROUP=P0
    test_merge_backup_with_multi_threads,multi_threads=True,threads_count=2,items=100000,GROUP=P1
    test_merge_backup_with_multi_threads,multi_threads=True,threads_count=4,items=100000,GROUP=P1
    test_merge_backup_with_partial_backup,items=100000,number_of_backups=2,GROUP=P1
    test_merge_backup_with_merge_kill_and_re_merge,items=100000,number_of_backups=2,GROUP=P1
    test_merge_backup_with_purge_deleted_keys,items=100000,GROUP=P1
    test_merge_backup_with_failover_logs,items=100000,GROUP=P1
    test_backup_restore_with_deletes,items=100000,GROUP=P0
    test_backupmgr_with_short_option,repo=r,GROUP=P1,items=100000
    test_backupmgr_with_short_option,archive=a,GROUP=P1,items=100000
    test_backupmgr_with_short_option,repo=r,GROUP=P1,items=100000
    test_backupmgr_with_short_option,cluster=c,GROUP=P1,items=100000
    test_backupmgr_with_short_option,bkusername=u,GROUP=P1,items=100000
    test_backupmgr_with_short_option,bkpassword=p,GROUP=P1,items=100000
    test_backupmgr_with_short_option,command=restore,repo=r,GROUP=P1,items=100000
    test_backupmgr_with_short_option,command=restore,archive=a,GROUP=P1,items=100000
    test_backupmgr_with_short_option,command=restore,repo=r,GROUP=P1,items=100000
    test_backupmgr_with_short_option,command=restore,cluster=c,GROUP=P1,items=100000
    test_backupmgr_with_short_option,command=restore,bkusername=u,GROUP=P1,items=100000
    test_backupmgr_with_short_option,command=restore,bkpassword=p,GROUP=P1,items=100000
    test_cbbackupmgr_with_eventing,default_bucket=False,dataset=default,GROUP=P0,backup_before_eventing=True,items=100000
    test_backup_purge,purge=True,items=500000,GROUP=P0
