ent_backup_restore.enterprise_backup_restore_test.EnterpriseBackupRestoreTest:
    test_cbbackupmgr_collect_logs,GROUP=P0,items=100000
    test_cbbackupmgr_collect_logs,no-output-flag=True,GROUP=P0,items=100000
    test_cbbackupmgr_collect_logs,nodes_init=1,ex-logs-path=logs,GROUP=P0,items=100000
    test_cbbackupmgr_collect_logs,nodes_init=1,ex-logs-path=relativepath,GROUP=P1,items=100000
    test_cbbackupmgr_collect_logs,nodes_init=1,ex-logs-path=non-exist-dir,GROUP=P1,items=100000
    test_cbbackupmgr_collect_logs,nodes_init=1,GROUP=P1,ex-logs-path=_12#-test,items=100000
    test_cbbackupmgr_collect_logs,nodes_init=1,GROUP=P1,ex-logs-path=l1234,items=100000
    test_cbbackupmgr_collect_logs,nodes_init=1,GROUP=P1,ex-logs-path=LOGS,items=100000
    test_cbbackupmgr_collect_logs,nodes_init=1,GROUP=P1,ex-logs-path=spa\ ce,items=100000
    test_cbbackupmgr_collect_logs,nodes_init=1,GROUP=P1,log-archive-env=True,items=100000
    test_cbbackupmgr_collect_logs,nodes_init=1,GROUP=P1,log-archive-env=True,ex-logs-path=logs,items=100000
    test_cbbackupmgr_restore_with_ttl,items=100000
    test_cbbackupmgr_restore_with_ttl,replace-ttl=add-none,GROUP=P0,items=100000
    test_cbbackupmgr_restore_with_ttl,replace-ttl=add-none,GROUP=P1,passwd-env=True,items=100000
    test_cbbackupmgr_restore_with_ttl,replace-ttl=add-none,GROUP=P1,passwd-env=True,user-env=True,items=100000
    test_cbbackupmgr_restore_with_ttl,replace-ttl=hello,GROUP=P0,should-fail=True,items=100000
    test_cbbackupmgr_restore_with_ttl,replace-ttl=empty-flag,GROUP=P0,replace-ttl-with=60,should-fail=True,items=100000
    test_cbbackupmgr_restore_with_ttl,replace-ttl=all,GROUP=P0,replace-ttl-with=abc,should-fail=True,items=100000
    test_cbbackupmgr_restore_with_ttl,replace-ttl=all,GROUP=P1,replace-ttl-with=300,items=100000
    test_cbbackupmgr_restore_with_ttl,replace-ttl=all,GROUP=P1,replace-ttl-with=400,items=100000
    test_cbbackupmgr_restore_with_ttl,replace-ttl=all,GROUP=P1,replace-ttl-with=300,bk-with-ttl=120,items=100000
    test_cbbackupmgr_restore_with_ttl,replace-ttl=all,GROUP=P1,replace-ttl-with=300,bk-with-ttl=600,items=100000
    test_cbbackupmgr_restore_with_ttl,replace-ttl=expired,GROUP=P0,bk-with-ttl=60,replace-ttl-with=0,items=100000
    test_cbbackupmgr_restore_with_ttl,replace-ttl=expired,GROUP=P0,replace-ttl-with=300,items=100000
    test_cbbackupmgr_restore_with_ttl,replace-ttl=expired,GROUP=P1,replace-ttl-with=400,items=100000
    test_cbbackupmgr_restore_with_ttl,replace-ttl=expired,GROUP=P1,replace-ttl-with=300,bk-with-ttl=120,items=100000
    test_cbbackupmgr_restore_with_ttl,replace-ttl=expired,GROUP=P1,replace-ttl-with=300,bk-with-ttl=600,items=100000
    test_cbbackupmgr_restore_with_ttl,replace-ttl=expired,GROUP=P1,replace-ttl-with=-300,should-fail=True,items=100000
