ent_backup_restore.backup_service_test.BackupServiceTest:
    test_correct_buckets_backed_up,all_buckets=False,standard_buckets=3,first_test=True,bucket_storage=couchstore,bucket_size=100,items=100000
    test_correct_buckets_backed_up,all_buckets=True,standard_buckets=3,bucket_storage=couchstore,bucket_size=100,items=100000
    test_invalid_repository,items=100000
    test_invalid_cloud_repository,objstore_provider=s3,items=100000
    test_valid_repository,standard_buckets=1,items=100000
    test_valid_cloud_repository,objstore_provider=s3,standard_buckets=1,items=100000
    test_pause_and_resume_repository,items=100000
    test_apply_plan_to_repository,items=100000
    test_importing_repository,items=100000
    test_importing_repository,objstore_provider=s3,items=100000
    test_importing_sensitive_repository,items=100000
    test_importing_read_only_repository,items=100000
    test_one_off_backup,full_backup=True,items=100000
    test_one_off_backup,full_backup=True,objstore_provider=s3,items=100000
    test_one_off_backup,full_backup=False,items=100000
    test_one_off_backup,full_backup=False,objstore_provider=s3,items=100000
    test_one_off_incr_backup,items=100000
    test_one_off_incr_backup,objstore_provider=s3,items=100000
    test_one_off_merge,items=100000
    test_one_off_cloud_merge_fails,objstore_provider=s3,items=100000
    test_one_off_restore,items=100000
    test_one_off_restore,objstore_provider=s3,items=100000
    test_invalid_tasks,standard_buckets=3,bucket_storage=couchstore,bucket_size=100,items=100000
    test_invalid_tasks,standard_buckets=3,objstore_provider=s3,bucket_storage=couchstore,bucket_size=100,items=100000
    test_user_warned_if_bucket_no_longer_exists,standard_buckets=3,bucket_storage=couchstore,bucket_size=100,items=100000
    test_user_warned_if_bucket_no_longer_exists,standard_buckets=3,objstore_provider=s3,bucket_storage=couchstore,bucket_size=100,items=100000
    test_archived_repository,items=100000
    test_delete_archived_repository,items=100000
    test_delete_archived_repository,remove_repository=True,items=100000
    test_delete_archived_repository,objstore_provider=s3,items=100000
    test_delete_archived_repository,objstore_provider=s3,remove_repository=True,items=100000
    test_delete_active_repository,items=100000
    test_manually_deleting_archive_location,items=100000
    test_manually_deleting_staging_directory,objstore_provider=s3,items=100000
    test_bad_archive_locations,items=100000
    test_health_indicators,items=100000
    test_user_can_history_info_examine_restore_from_archived_repository,items=100000
    test_user_can_history_info_examine_restore_from_archived_repository,objstore_provider=s3,last_test=True,items=100000
    test_creating_repo_simultaneously_on_two_nodes,items=100000
