tuqquery.tuq_sanitize.QuerySanitizeTests:
    test_sanitize_basic
    test_sanitize_dml_statements
    test_sanitize_complex
    test_sanitize_insert_upsert
    test_sanitize_merge
    test_sanitize_null_boolean
    test_sanitize_nested_functions
    test_sanitize_ddl_noop
    test_sanitize_dcl_noop
