tuqquery.tuq_auto_prepare.QueryAutoPrepareTests:
    test_ps_rbac_ro_cannot_update
    test_ps_rbac_admin_can_update
    test_ps_rbac_ro_cannot_drop_query_metadata_bucket
    test_ps_rbac_ro_cannot_delete_query_metadata_docs
