tuqquery.tuq_magma.QueryMagmaTests:
    test_insert_returning_elements,GROUP=P0
    test_update_where,GROUP=P0
    test_delete_where_clause_json,GROUP=P0
    test_merge_update_match_set,GROUP=P0
    test_group_by_having,GROUP=P0
    test_union_aggr_fns,GROUP=P0
    test_basic_cte,GROUP=P0
    test_udf_letting,GROUP=P0
    test_txns,GROUP=P0