# Sparse ANN-vs-KNN misc validation (no ground-truth comparisons)
tuqquery.tuq_vectorsearch.VectorSearchTests:
    test_ann_nulls,vector_type=sparse,distance=DOT,nprobes=100,train=5000
    test_ann_ann,vector_type=sparse,distance=DOT,nprobes=100
    test_ann_predicate_order,vector_type=sparse,distance=DOT,nprobes=100
    test_ann_array_any,vector_type=sparse,distance=DOT,nprobes=100
    test_ann_array_every,vector_type=sparse,distance=DOT,nprobes=100
    test_ann_unnest,vector_type=sparse,distance=DOT,nprobes=100
    test_ann_subquery_from,vector_type=sparse,distance=DOT,nprobes=100
    test_ann_subquery,vector_type=sparse,distance=DOT,nprobes=100
    test_ann_subquery_correlated,vector_type=sparse,distance=DOT,nprobes=100
