# Run the vector search tests with sparse vectors and DOT distance.
# with following options:
# - use_xattr=true, use_base64=true
# - use_xattr=true, use_base64=false
# - use_xattr=false, use_base64=true
# - use_xattr=false, use_base64=false
tuqquery.tuq_vectorsearch.VectorSearchTests:
    test_knn_distances_sparse,vector_type=sparse,distance=DOT
    test_knn_search,vector_type=sparse,distance=DOT
    tuq_ann_search,vector_type=sparse,distance=DOT,nprobes=24,train=20000
    tuq_ann_search,vector_type=sparse,distance=DOT,nprobes=24,use_bhive=True,train=20000
