tuqquery.tuq_vectorsearch.VectorSearchTests:
    test_ann_search,distance=L2_SQUARED,description=IVF,RaBitQ,nprobes=20,dimension=1024,train=1000,GROUP=P0
    test_ann_search,distance=EUCLIDEAN,description=IVF,RaBitQ,nprobes=20,dimension=1024,train=1000,GROUP=P0
    test_ann_search,distance=L2_SQUARED,description=IVF,RaBitQ,nprobes=20,dimension=1024,train=1000,index_order=lead,GROUP=P0
    test_ann_search,distance=EUCLIDEAN,description=IVF,RaBitQ,nprobes=20,dimension=1024,train=1000,index_order=mid,GROUP=P0
    test_ann_search,distance=L2_SQUARED,description=IVF,RaBitQ,nprobes=20,dimension=1024,train=1000,use_bhive=True,GROUP=P0
    test_ann_search,distance=EUCLIDEAN,description=IVF,RaBitQ,nprobes=20,dimension=1024,train=1000,use_bhive=True,GROUP=P0
