# Iceberg tests — BigLake Metastore catalog

tuqquery.tuq_iceberg.IcebergQueryTests:
    test_iceberg_select_count,catalog_type=BIGLAKE_METASTORE,default_bucket=False,GROUP=ICEBERG
    test_iceberg_select_projection,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_select_filter,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_select_reviews_array,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_select_star_nested_structure,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_queries_from_file,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_select_reviews_nested_list_template,data_type=nested_review,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_alter_catalog_invalid_credentials,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_drop_order_dependencies,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_null_values,data_type=null_values,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_diverse_datatypes,data_type=diverse_datatypes,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_schema_evolution,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_mixed_types,data_type=mixed_types,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_snapshot_id,data_type=snapshot,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_snapshot_timestamp,data_type=snapshot,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_predicate_pushdown,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_query_context,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_join_different_bucket,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_join_same_bucket_different_scope,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
    test_iceberg_join_same_bucket_same_scope,catalog_type=BIGLAKE_METASTORE,GROUP=ICEBERG
