tuqquery.tuq_auto_prepare.QueryAutoPrepareTests:
    test_plan_stability_ad_hoc_to_prepared_only
tuqquery.tuq_iceberg.IcebergQueryTests:
    test_iceberg_select_count,catalog_type=S3_TABLES,default_bucket=False,sigv4_signing_name=s3tables
tuqquery.tuq_vectorsearch.VectorSearchTests:
    test_ann_nulls,vector_type=sparse,distance=DOT,nprobes=200,train=5000
tuqquery.tuq_sanitize.QuerySanitizeTests:
    test_sanitize_basic
tuqquery.tuq_vectorsearch.VectorSearchTests:
    test_knn_distances_sparse,vector_type=sparse,distance=DOT,nprobes=200
tuqquery.tuq_ranking_fusion.QueryRankingFusionTests:
    test_rsf_dense_sparse
    test_rrf_dense_sparse
tuqquery.n1ql_encryption_at_rest.QueryEncryptionAtRestTests:
    test_query_request_log_files_encrypted,enable_log_encryption_at_rest=True,json_template=Hotel,nodes_init=3,services_init=kv:n1ql:index-kv:n1ql:index-kv:n1ql:index,num_index_replica=1,skip_load=True,GROUP=P0,java_sdk_client=True,use_magma_loader=True,create_primary_index=False,sleep_after_bucket_deletion=30
    test_query_log_encryption_key_rotation,enable_log_encryption_at_rest=True,json_template=Hotel,nodes_init=3,services_init=kv:n1ql:index-kv:n1ql:index-kv:n1ql:index,num_index_replica=1,skip_load=True,GROUP=P0,java_sdk_client=True,use_magma_loader=True,create_primary_index=False,sleep_after_bucket_deletion=30
    test_query_log_encryption_force_reencryption,enable_log_encryption_at_rest=True,json_template=Hotel,nodes_init=3,services_init=kv:n1ql:index-kv:n1ql:index-kv:n1ql:index,num_index_replica=1,skip_load=True,GROUP=P0,java_sdk_client=True,use_magma_loader=True,sleep_after_bucket_deletion=30,create_primary_index=False
 