RABBITMQ_IP = '127.0.0.1'
RESULT_CACHE_IP ='127.0.0.1'
RESULT_CACHE_PORT ='11211'
OBJECT_CACHE_IP = "127.0.0.1"
OBJECT_CACHE_PORT = "11211"
COUCHBASE_IP = '127.0.0.1'
COUCHBASE_PORT = '9000'
COUCHBASE_USER = "Administrator"
COUCHBASE_PWD = "asdasd"
SSH_USER = "root"
SSH_PASSWORD = "password"
WORKERS = ['127.0.0.1']
ATOP_LOG_FILE = "/tmp/atop-node.log"
LOGDIR="logs"  # relative to current dir

#Backup Config
ENABLE_BACKUPS = False
BACKUP_DIR = "/tmp/backup"
BACKUP_NODE_IP = "127.0.0.1"
BACKUP_NODE_SSH_USER = "root"
BACKUP_NODE_SSH_PWD = "password"
