#!/usr/bin/env python

import sys
import unittest
sys.path.append("lib")
sys.path.append("pytests")

from memcachedops.set_get_test import SimpleSetGetTest

if __name__ == '__main__':
    suite = unittest.TestLoader().loadTestsFromTestCase(SimpleSetGetTest)
    result = unittest.TextTestRunner(verbosity=0).run(suite)
    if result.failures or result.errors:
        sys.exit(-1)
    sys.exit(0)
