#Python3 upgrade testing for tools
#cbbackup
clitest.couchbase_clitest.CouchbaseCliTest:
    test_directory_backup_structure,backup_cmd=cbbackup,num_standard_buckets=3,num_backup_bucket=3,load_all=true
#cbcompact
ent_backup_restore.enterprise_backup_restore_test.EnterpriseBackupRestoreTest:
    test_merge_backup_with_purge_deleted_keys,items=1000
#cbrecovery: this test needs at least 8 nodes so it could failover 2 and add 2 at the same time.  It covers in backup_recovery
#cbRecoverytests.cbrecovery.restart_cbrecover_multiple_failover_swapout_reb_routine,items=50000,rdirection=unidirection,ctopology=chain,failover=source,fail_count=2,add_count=2,max_verify=10000,when_step=recovery_when_rebalance
#cbtransfer
transfer.cbtransfertests.CBTransferTests.test_load_regexp

clitest.collectinfotest.CollectinfoTests:
    collectinfo_test,node_down=True,GROUP=P0
# test cli  with collecton
clitest.couchbase_clitest_with_collections.CouchbaseCliTestWithCollections:
    # use cli
    test_cbstats_with_collection,start_with_cluster=false,custom_scopes=true,custom_collections=true,check_collections=true,use_rest=false
    test_cbworkloadgen_with_collection,start_with_cluster=false,load_to_default_collections=true,use_rest=false
    test_cbcollectinfo_with_collection,start_with_cluster=false,use_rest=false
    test_view_cbcollectinfo_with_collection,filename=collectInfo,use_rest=false,bucket_storage=couchstore
    test_drop_sc,start_with_cluster=false,drop_collections=true,custom_scopes=true,custom_collections=true,use_rest=false

clitest.couchbase_clitest_with_collections.XdcrCLITest:
    testXdcrReplication,servers=2,xdcr-cluster-name=remote,xdcr-hostname=3,xdcr-username=Administrator,xdcr-password=password,secure-connection=half,xdcr-certificate=cert.pem,xdcr-from-bucket=default,xdcr-to-bucket=default,custom_scopes=true,custom_collections=true

# test import export
clitest.importexporttest.ImportExportTests:
    #use rest
    test_export_with_collection,start_with_cluster=false

    # use cli
    test_export_with_collection,start_with_cluster=false

