"""
gsi_encryption_at_rest.py: Tests for GSI with Encryption at Rest enabled

Tests validate index creation, scans, and encryption configuration for various storage
types (MOI and Plasma) with encryption at rest enabled on buckets.

Encryption setup is handled by basetestcase.py when enable_encryption_at_rest=True.
This test uses self.encryption_at_rest_id (set by base class) to enable bucket encryption.

Supported storage types:
- memory_optimized (MOI) - in-memory storage
- forestdb (Plasma) - persistent storage

__author__ = "Pavan PB"
__maintainer = "Pavan PB"
__email__ = "pavan.pb@couchbase.com"
__git_user__ = "pavan-couchbase"
__created_on__ = "16/04/26"
"""

import json
import random
import re
import string
from couchbase_helper.documentgenerator import SDKDataLoader
from couchbase_helper.query_definitions import QueryDefinition
from .base_gsi import BaseSecondaryIndexingTests
from membase.api.rest_client import RestConnection
from lib.membase.helper.encryption_at_rest_helper import EncryptionUtil


class GSIEncryptionAtRest(BaseSecondaryIndexingTests):
    UUID_PATTERN = re.compile(
        r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    )

    """
    Test class for GSI operations with Encryption at Rest enabled.
    
    Tests validate:
    - Encryption at rest configuration on buckets
    - Index creation with various types and replica counts on different storage types
    - Scan operations and result validation
    - Index stats verification (num_requests)
    
    Supported storage types:
    - memory_optimized (MOI) - in-memory indexes
    - forestdb (Plasma) - persistent indexes
    """
    
    def setUp(self):
        super(GSIEncryptionAtRest, self).setUp()
        self.log.info("==============  GSIEncryptionAtRest setup has started ==============")
        self.rest.delete_all_buckets()
        self.bucket_count = self.input.param("bucket_count", 1)
        self.num_scopes = self.input.param("num_scopes", 1)
        self.num_collections = self.input.param("num_collections", 1)
        self.use_default_collection_only = self.input.param("use_default_collection_only", True)
        self.num_of_docs_per_collection = self.input.param("num_of_docs_per_collection", 10000)
        self.json_template = self.input.param("json_template", "Hotel")
        self.defer_build = self.input.param("defer_build", False)
        self.encrypt_all_buckets = self.input.param("encrypt_all_buckets", True)
        self.log.info("==============  GSIEncryptionAtRest setup has completed ==============")

    def tearDown(self):
        self.log.info("==============  GSIEncryptionAtRest tearDown has started ==============")
        super(GSIEncryptionAtRest, self).tearDown()
        self.log.info("==============  GSIEncryptionAtRest tearDown has completed ==============")

    def suite_tearDown(self):
        self.log.info("==============  GSIEncryptionAtRest suite_tearDown has started ==============")
        super(GSIEncryptionAtRest, self).suite_tearDown()
        self.log.info("==============  GSIEncryptionAtRest suite_tearDown has completed ==============")

    def suite_setUp(self):
        self.log.info("==============  GSIEncryptionAtRest suite_setUp has started ==============")
        super(GSIEncryptionAtRest, self).suite_setUp()
        self.log.info("==============  GSIEncryptionAtRest suite_setUp has completed ==============")

    def _create_encrypted_bucket(self):
        """
        Create bucket and enable encryption at rest using the encryption_at_rest_id
        generated by basetestcase.py (via enable_encryption_at_rest=True param).
        
        Returns:
            str: Name of the created bucket
        """
        bucket_name = self.test_bucket
        self.bucket_params = self._create_bucket_params(
            server=self.master, 
            size=self.bucket_size,
            replicas=self.num_replicas, 
            bucket_type=self.bucket_type,
            enable_replica_index=self.enable_replica_index,
            eviction_policy=self.eviction_policy, 
            lww=self.lww
        )
        self.cluster.create_standard_bucket(name=bucket_name, port=11222, bucket_params=self.bucket_params)
        self.buckets = self.rest.get_buckets()
        
        # Enable encryption at rest on the bucket using the secret id from base class
        if hasattr(self, 'encryption_at_rest_id') and self.encryption_at_rest_id is not None:
            self.log.info(f"Enabling encryption at rest on bucket '{bucket_name}' with secret id {self.encryption_at_rest_id}")
            status, response = self.rest.enable_bucket_encryption(bucket_name, self.encryption_at_rest_id)
            if not status:
                raise Exception(f"Failed to enable encryption at rest on bucket {bucket_name}: {response}")
            self.log.info(f"Encryption at rest enabled successfully on bucket '{bucket_name}'")
        else:
            raise Exception("encryption_at_rest_id not available. Ensure enable_encryption_at_rest=True is set in test params")
        
        return bucket_name

    def _validate_bucket_encryption(self, bucket_name):
        """
        Validate that the bucket has encryption at rest enabled with the correct key id.
        
        Args:
            bucket_name: Name of the bucket to validate
        """
        bucket_info = self.rest.get_bucket_json(bucket_name)
        encryption_key_id = bucket_info.get('encryptionAtRestKeyId', None)
        self.log.info(f"Bucket '{bucket_name}' encryptionAtRestKeyId: {encryption_key_id}")
        
        if encryption_key_id is None or encryption_key_id == -1:
            raise Exception(f"Bucket '{bucket_name}' does not have encryption at rest enabled")
        
        if hasattr(self, 'encryption_at_rest_id') and self.encryption_at_rest_id is not None and encryption_key_id != self.encryption_at_rest_id:
            raise Exception(f"Bucket encryption key id {encryption_key_id} does not match expected {self.encryption_at_rest_id}")
        
        self.log.info(f"Bucket '{bucket_name}' encryption at rest validation passed")

    def _prepare_namespaces(self, bucket_name):
        """
        Prepare namespaces based on test parameters.
        
        Args:
            bucket_name: Name of the bucket
            
        Returns:
            list: List of namespace strings
        """
        self.namespaces = []
        
        if self.use_default_collection_only:
            # Use default scope and collection
            namespace = f"default:{bucket_name}._default._default"
            self.namespaces.append(namespace)
            self.log.info(f"Using default collection namespace: {namespace}")
        else:
            # Create custom scopes and collections
            self.prepare_collection_for_indexing(
                num_scopes=self.num_scopes,
                num_collections=self.num_collections,
                num_of_docs_per_collection=self.num_of_docs_per_collection,
                json_template=self.json_template,
                bucket_name=bucket_name
            )
        
        return self.namespaces

    def _create_indexes(self, namespace, index_nodes):
        """
        Create indexes using gsi_util_obj patterns similar to gsi_file_based_rebalance.py.
        
        Creates one set of indexes with num_replica=self.num_index_replica.
        If defer_build=True, creates deferred indexes and builds them separately.
        
        Args:
            namespace: Namespace string for index creation
            index_nodes: List of index nodes for deployment
            
        Returns:
            tuple: (select_queries set, create_queries list, deferred_definitions list)
        """
        select_queries = set()
        create_queries = []
        deferred_definitions = []
        query_node = self.get_nodes_from_services_map(service_type="n1ql")
        deploy_nodes = [f"{node.ip}:{self.node_port}" for node in index_nodes]
        
        for namespace_iter in self.namespaces:
            # Generate unique prefix
            prefix = 'ear_' + ''.join(random.choices(string.ascii_letters + string.digits, k=5))
            
            # Get index definitions based on json_template
            query_definitions = self.gsi_util_obj.get_index_definition_list(
                dataset=self.json_template,
                prefix=prefix,
                skip_primary=False
            )
            
            # Get select queries for validation
            select_queries.update(
                self.gsi_util_obj.get_select_queries(
                    definition_list=query_definitions,
                    namespace=namespace_iter
                )
            )
            
            # Get create index queries with specified replica count
            queries = self.gsi_util_obj.get_create_index_list(
                definition_list=query_definitions,
                namespace=namespace_iter,
                num_replica=self.num_index_replica,
                deploy_node_info=deploy_nodes,
                defer_build=self.defer_build
            )
            
            # Create indexes
            self.gsi_util_obj.create_gsi_indexes(
                create_queries=queries,
                database=namespace_iter,
                query_node=query_node
            )
            
            create_queries.extend(queries)
            
            # Track deferred definitions for later build
            if self.defer_build:
                deferred_definitions.extend(query_definitions)
        
        self.log.info(f"Created {len(create_queries)} indexes with num_replica={self.num_index_replica}")
        return select_queries, create_queries, deferred_definitions

    def _build_deferred_indexes(self, namespace, deferred_definitions):
        """
        Build deferred indexes.
        
        Args:
            namespace: Namespace string for index creation
            deferred_definitions: List of deferred index definitions
        """
        if deferred_definitions:
            build_query = self.gsi_util_obj.get_build_indexes_query(
                definition_list=deferred_definitions,
                namespace=namespace
            )
            self.log.info(f"Building deferred indexes: {build_query}")
            self.run_cbq_query(query=build_query)

    def _capture_scan_stats(self):
        """
        Capture current scan stats for all indexes.
        
        Returns:
            dict: Dictionary of index name to num_requests before scans
        """
        stats_before = {}
        stats_map = self.get_index_stats(perNode=True)
        
        for node in stats_map:
            for keyspace in stats_map[node]:
                for index_name in stats_map[node][keyspace]:
                    if index_name not in stats_before:
                        stats_before[index_name] = 0
                    if 'num_requests' in stats_map[node][keyspace][index_name]:
                        stats_before[index_name] += stats_map[node][keyspace][index_name]['num_requests']
        
        return stats_before

    def _run_and_validate_scans(self, select_queries, expected_doc_count):
        """
        Run scan queries and validate results.
        
        Args:
            select_queries: Set of select query strings
            expected_doc_count: Expected number of documents in results
        """
        self.log.info(f"Running {len(select_queries)} scan queries for validation")
        
        for query in select_queries:
            self.log.info(f"Running scan query: {query[:100]}...")
            result = self.run_cbq_query(query=query, scan_consistency='request_plus')
            
            # Validate result is returned
            self.assertIn('results', result, f"No results returned for scan query: {query[:100]}")
            
            # Log result count
            result_count = len(result.get('results', []))
            if result_count > 0:
                self.log.info(f"Scan query returned {result_count} results")
            else:
                self.log.info(f"Scan query completed (no results returned)")

    def _validate_scan_stats_increment(self, stats_before):
        """
        Validate that num_requests increased after scans.
        
        Args:
            stats_before: Stats captured before scans
        """
        stats_after = self.get_index_stats(perNode=True)
        
        # Aggregate stats after scans
        stats_after_agg = {}
        for node in stats_after:
            for keyspace in stats_after[node]:
                for index_name in stats_after[node][keyspace]:
                    if index_name not in stats_after_agg:
                        stats_after_agg[index_name] = 0
                    if 'num_requests' in stats_after[node][keyspace][index_name]:
                        stats_after_agg[index_name] += stats_after[node][keyspace][index_name]['num_requests']
        
        # Check that at least some indexes show increased scan activity
        total_before = sum(stats_before.values())
        total_after = sum(stats_after_agg.values())
        
        self.assertGreater(total_after, total_before,
            f"Total num_requests did not increase after scans (before={total_before}, after={total_after})")
        
        self.log.info(f"Total num_requests: before={total_before}, after={total_after}")
        self.log.info(f"Scan activity validated across {len(stats_after_agg)} indexes")

    def _create_bucket_with_encryption(self, bucket_name, enable_encryption=True):
        """
        Create a bucket with optional encryption at rest.
        
        Args:
            bucket_name: Name of the bucket to create
            enable_encryption: Whether to enable encryption at rest
            
        Returns:
            str: Name of the created bucket
        """
        self.bucket_params = self._create_bucket_params(
            server=self.master, 
            size=self.bucket_size,
            replicas=self.num_replicas, 
            bucket_type=self.bucket_type,
            enable_replica_index=self.enable_replica_index,
            eviction_policy=self.eviction_policy, 
            lww=self.lww
        )
        self.cluster.create_standard_bucket(name=bucket_name, port=11222, bucket_params=self.bucket_params)
        self.buckets = self.rest.get_buckets()
        
        if enable_encryption:
            if hasattr(self, 'encryption_at_rest_id') and self.encryption_at_rest_id is not None:
                self.log.info(f"Enabling encryption at rest on bucket '{bucket_name}' with secret id {self.encryption_at_rest_id}")
                status, response = self.rest.enable_bucket_encryption(bucket_name, self.encryption_at_rest_id)
                if not status:
                    raise Exception(f"Failed to enable encryption at rest on bucket {bucket_name}: {response}")
                self.log.info(f"Encryption at rest enabled successfully on bucket '{bucket_name}'")
            else:
                raise Exception("encryption_at_rest_id not available. Ensure enable_encryption_at_rest=True is set in test params")
        else:
            self.log.info(f"Created bucket '{bucket_name}' without encryption at rest")
        
        return bucket_name

    def _create_new_encryption_key(self):
        """
        Create a new encryption secret/key for key rotation.
        
        Returns:
            int: The new encryption key ID
        """
        params = EncryptionUtil.create_secret_params(
            name=EncryptionUtil.generate_random_name("RotationKey"),
            rotationIntervalInSeconds=self.secret_rotation_interval if hasattr(self, 'secret_rotation_interval') else 60
        )
        self.log.info(f"Creating new encryption key with params: {params}")
        status, response = self.rest.create_secret(params)
        if not status:
            raise Exception(f"Failed to create new encryption key: {response}")
        
        response_dict = json.loads(response)
        new_key_id = response_dict.get('id')
        if new_key_id is None:
            raise Exception(f"New encryption key created but no ID returned: {response}")
        
        self.log.info(f"Created new encryption key with ID: {new_key_id}")
        return new_key_id

    def _rotate_bucket_encryption_key(self, bucket_name, new_key_id, dek_rotation_interval=120, dek_lifetime=120):
        """
        Rotate the encryption key for a bucket to a new key using DEK rotation.
        
        This sets up automatic DEK rotation by:
        1. Setting the DEK rotation interval
        2. Setting the DEK lifetime
        
        Args:
            bucket_name: Name of the bucket
            new_key_id: The new encryption key ID to use
            dek_rotation_interval: DEK rotation interval in seconds (default: 120)
            dek_lifetime: DEK lifetime in seconds (default: 120)
        """
        self.log.info(f"Rotating bucket '{bucket_name}' encryption to key ID {new_key_id}")
        
        # Set DEK rotation interval
        self.log.info(f"Setting DEK rotation interval to {dek_rotation_interval} seconds")
        status, response = self.rest.set_bucket_dek_rotation_interval(bucket_name, dek_rotation_interval)
        if not status:
            raise Exception(f"Failed to set DEK rotation interval: {response}")
        
        # Set DEK lifetime
        self.log.info(f"Setting DEK lifetime to {dek_lifetime} seconds")
        status, response = self.rest.set_bucket_dek_lifetime(bucket_name, dek_lifetime)
        if not status:
            raise Exception(f"Failed to set DEK lifetime: {response}")
        
        self.log.info(f"Bucket '{bucket_name}' DEK rotation configured with interval={dek_rotation_interval}s, lifetime={dek_lifetime}s")

    def _extract_header_key_id_candidates(self, value, candidates):
        """
        Extract header-visible key identifiers from nested secret metadata.
        """
        if isinstance(value, dict):
            for nested_key, nested_value in value.items():
                key_lower = nested_key.lower()
                if isinstance(nested_value, (str, int)):
                    value_str = str(nested_value)
                    if key_lower.endswith("id") or self.UUID_PATTERN.match(value_str):
                        candidates.add(value_str)
                self._extract_header_key_id_candidates(nested_value, candidates)
        elif isinstance(value, list):
            for item in value:
                self._extract_header_key_id_candidates(item, candidates)
        elif isinstance(value, str) and self.UUID_PATTERN.match(value):
            candidates.add(value)

    def _get_expected_header_key_ids(self, expected_key_id):
        """
        Resolve the key identifiers that can appear in encrypted file headers.
        """
        if expected_key_id in [None, ""]:
            return []

        candidates = {str(expected_key_id)}
        try:
            status, response = self.rest.get_specific_secret(expected_key_id)
            if not status:
                self.log.warning(
                    f"Failed to fetch secret details for key ID {expected_key_id}; "
                    f"falling back to direct key ID matching"
                )
                return list(candidates)

            if isinstance(response, bytes):
                response = response.decode("utf-8", errors="replace")
            response_dict = json.loads(response) if isinstance(response, str) else response
            self._extract_header_key_id_candidates(response_dict, candidates)
        except Exception as err:
            self.log.warning(
                f"Unable to resolve header key identifiers for key ID {expected_key_id}: {err}"
            )

        return sorted(candidates)

    def _extract_in_use_key_ids(self, value, key_ids):
        """
        Extract key IDs from the indexer GetInUseKeys response.
        """
        if isinstance(value, dict):
            for nested_key, nested_value in value.items():
                if nested_key.lower().endswith("keyid") and nested_value not in [None, ""]:
                    key_ids.add(str(nested_value))
                self._extract_in_use_key_ids(nested_value, key_ids)
        elif isinstance(value, list):
            for item in value:
                self._extract_in_use_key_ids(item, key_ids)
        elif isinstance(value, (str, int)) and value not in [None, ""]:
            value_str = str(value)
            if self.UUID_PATTERN.match(value_str):
                key_ids.add(value_str)

    def _get_indexer_in_use_key_ids(self, index_nodes):
        """
        Query all index nodes and return the union of in-use key IDs.
        """
        key_ids = set()
        for index_node in index_nodes:
            rest = RestConnection(index_node)
            status, response = rest.get_indexer_in_use_encryption_keys()
            if not status:
                raise Exception(
                    f"Failed to fetch in-use encryption keys from index node {index_node.ip}: {response}"
                )
            self._extract_in_use_key_ids(response, key_ids)

        if not key_ids:
            raise Exception("Indexer GetInUseKeys returned no key IDs")

        resolved_key_ids = sorted(key_ids)
        self.log.info(f"Resolved in-use indexer key IDs: {resolved_key_ids}")
        return resolved_key_ids

    def _get_new_indexer_in_use_key_ids(self, index_nodes, previous_key_ids):
        """
        Query current in-use key IDs and return only the newly introduced IDs.
        """
        current_key_ids = set(self._get_indexer_in_use_key_ids(index_nodes))
        previous_key_ids = {str(key_id) for key_id in previous_key_ids}
        new_key_ids = sorted(current_key_ids.difference(previous_key_ids))
        self.log.info(
            f"Current in-use indexer key IDs: {sorted(current_key_ids)}, "
            f"previous key IDs: {sorted(previous_key_ids)}, new key IDs: {new_key_ids}"
        )
        return new_key_ids

    def _validate_file_encryption_with_key(self, index_nodes, expected_key_id=None, step_prefix=""):
        """
        Validate file encryption and optionally check for an expected key ID in headers.
        
        Args:
            index_nodes: List of index nodes
            expected_key_id: Optional expected encryption key ID in file headers
            step_prefix: Prefix for logging steps
            
        Returns:
            bool: True if validation passed, False otherwise
        """
        if expected_key_id is None:
            self.log.info(f"{step_prefix}Validating file encryption...")
            expected_header_key_ids = None
        elif isinstance(expected_key_id, (list, tuple, set)):
            expected_header_key_ids = [str(key_id) for key_id in expected_key_id if key_id not in [None, ""]]
            self.log.info(
                f"{step_prefix}Validating file encryption with expected key IDs {expected_header_key_ids}..."
            )
        else:
            expected_header_key_ids = self._get_expected_header_key_ids(expected_key_id)
            self.log.info(
                f"{step_prefix}Validating file encryption with expected key ID {expected_key_id} "
                f"using header key identifiers {expected_header_key_ids}..."
            )
        
        encryption_results = self.validate_file_encryption(
            index_nodes, expected_key_id=expected_header_key_ids
        )
        
        all_failed_files = []
        validation_passed = True
        
        for category, results in encryption_results.items():
            if category == "TODO":
                continue
            if isinstance(results, dict):
                for node, result in results.items():
                    status = result.get("status", "unknown")
                    if status == "passed":
                        failed_files = result.get("failed_files", [])
                        if failed_files:
                            self.log.warning(f"{step_prefix}{category} on {node}: PASSED with {len(failed_files)} issues")
                            for file_path, details in failed_files:
                                self.log.error(f"{step_prefix}ISSUE on {node}: {file_path} - {details}")
                                all_failed_files.append((node, file_path, details))
                        else:
                            self.log.info(f"{step_prefix}{category} on {node}: PASSED - All files encrypted with key ID {expected_key_id}")
                    elif status == "failed":
                        validation_passed = False
                        self.log.error(f"{step_prefix}{category} on {node}: FAILED - {result.get('reason', 'unknown')}")
                        failed_files = result.get("failed_files", [])
                        for file_path, details in failed_files:
                            self.log.error(f"{step_prefix}FAILED FILE: {file_path} - {details}")
                            all_failed_files.append((node, file_path, details))
                    elif status == "skipped":
                        self.log.warning(f"{step_prefix}{category} on {node}: SKIPPED - {result.get('reason', 'unknown')}")
        
        if all_failed_files:
            self.log.error(f"{step_prefix}Found {len(all_failed_files)} files with encryption issues")
        
        return validation_passed and not all_failed_files

    def test_gsi_encryption_at_rest_sanity(self):
        """
        Encryption at rest sanity test case - supports single or multiple buckets.
        
        Test validates:
        1. Encryption at rest is configured (key created by basetestcase.py)
        2. Buckets are created with encryption enabled based on bucket_count and encrypt_all_buckets params
        3. Indexer snapshot settings configured (persisted_snapshot.moi.interval=60000)
        4. Various index types are created successfully on the configured storage type
        5. Indexes reach "Ready" state
        6. SELECT queries for all indexes execute successfully and return results
        7. Item count validations (KV vs GSI counts, replica counts, no pending mutations)
        8. File encryption validation on disk
        
        Parameters:
        - bucket_count: Number of buckets to create (default: 1)
        - encrypt_all_buckets: If True, all buckets are encrypted. If False, only first bucket is encrypted.
        
        Storage types supported:
        - memory_optimized (MOI) - in-memory indexes
        - forestdb (Plasma) - persistent indexes
        """
        self.log.info("=" * 80)
        self.log.info("STARTING TEST: test_gsi_encryption_at_rest_sanity")
        self.log.info(f"Test parameters: gsi_type={self.gsi_type}, bucket_count={self.bucket_count}, encrypt_all_buckets={self.encrypt_all_buckets}")
        self.log.info("=" * 80)
        
        # ========== STEP 1: Verify index nodes ==========
        try:
            self.log.info("[STEP 1] Verifying index node availability...")
            index_nodes = self.get_nodes_from_services_map(service_type="index", get_all_nodes=True)
            self.log.info(f"[STEP 1] Found {len(index_nodes)} index nodes: {[node.ip for node in index_nodes]}")
            self.assertGreaterEqual(len(index_nodes), 2,
                f"Need at least 2 index nodes, found {len(index_nodes)}")
            self.log.info("[STEP 1] PASSED - Index node verification successful")
        except Exception as e:
            self.log.error(f"[STEP 1] FAILED - Index node verification failed: {str(e)}")
            raise
        
        # ========== STEP 2: Log storage type ==========
        self.log.info(f"[STEP 2] Storage engine: gsi_type={self.gsi_type}")
        self.log.info("[STEP 2] PASSED - Storage type confirmed")
        
        # ========== STEP 3: Verify encryption at rest parameter ==========
        try:
            self.log.info("[STEP 3] Verifying encryption at rest parameter...")
            if not self.enable_encryption_at_rest:
                self.log.info("[STEP 3] SKIPPED - Encryption at rest not enabled")
                self.skipTest("Encryption at rest not enabled. Set enable_encryption_at_rest=True")
            self.log.info("[STEP 3] PASSED - Encryption at rest parameter confirmed")
        except Exception as e:
            self.log.error(f"[STEP 3] FAILED - Encryption parameter verification failed: {str(e)}")
            raise
        
        # ========== STEP 4: Create buckets with encryption ==========
        bucket_names = []
        encrypted_bucket_names = []
        try:
            self.log.info(f"[STEP 4] Creating {self.bucket_count} bucket(s)...")
            for i in range(self.bucket_count):
                bucket_name = f"{self.test_bucket}_{i+1}" if self.bucket_count > 1 else self.test_bucket
                encrypt_this_bucket = self.encrypt_all_buckets or (i == 0)
                self.log.info(f"[STEP 4.{i+1}] Creating bucket '{bucket_name}' with encryption={encrypt_this_bucket}")
                
                self._create_bucket_with_encryption(bucket_name, enable_encryption=encrypt_this_bucket)
                bucket_names.append(bucket_name)
                if encrypt_this_bucket:
                    encrypted_bucket_names.append(bucket_name)
                
                # Validate bucket encryption status
                bucket_info = self.rest.get_bucket_json(bucket_name)
                encryption_key_id = bucket_info.get('encryptionAtRestKeyId', None)
                self.log.info(f"[STEP 4.{i+1}] Bucket '{bucket_name}' encryptionAtRestKeyId: {encryption_key_id}")
                
                if encrypt_this_bucket:
                    if encryption_key_id is None or encryption_key_id == -1:
                        raise Exception(f"Bucket '{bucket_name}' should have encryption enabled")
                else:
                    if encryption_key_id is not None and encryption_key_id != -1:
                        raise Exception(f"Bucket '{bucket_name}' should not have encryption enabled")
                
                self.log.info(f"[STEP 4.{i+1}] PASSED - Bucket '{bucket_name}' created successfully")
            
            self.log.info(f"[STEP 4] PASSED - Created {len(bucket_names)} bucket(s): {bucket_names}")
        except Exception as e:
            self.log.error(f"[STEP 4] FAILED - Bucket creation failed: {str(e)}")
            raise
        
        # ========== STEP 5: Set indexer snapshot settings ==========
        try:
            self.log.info("[STEP 5] Setting indexer snapshot settings for MOI...")
            for index_node in index_nodes:
                rest = RestConnection(index_node)
                rest.set_index_settings({"indexer.settings.persisted_snapshot.moi.interval": 60000})
                rest.set_index_settings({"indexer.settings.persisted_snapshot_init_build.moi.interval": 60000})
            self.log.info("[STEP 5] PASSED - Indexer snapshot settings configured (persisted_snapshot.moi.interval=60000, persisted_snapshot_init_build.moi.interval=60000)")
        except Exception as e:
            self.log.error(f"[STEP 5] FAILED - Indexer settings configuration failed: {str(e)}")
            raise
        
        # ========== STEP 6: Load documents and create indexes ==========
        select_queries = set()
        try:
            self.log.info(f"[STEP 6] Loading documents and creating indexes for {len(bucket_names)} bucket(s)...")

            # Step 6a: Load documents across all buckets in one pass
            try:
                self.log.info(
                    f"[STEP 6.a] Loading {self.num_of_docs_per_collection} documents into each bucket: {bucket_names}"
                )
                gen_create = SDKDataLoader(
                    num_ops=self.num_of_docs_per_collection,
                    percent_create=100,
                    percent_update=0,
                    percent_delete=0,
                    scope="_default",
                    collection="_default",
                    json_template=self.json_template,
                    output=True,
                    username=self.username,
                    password=self.password
                )
                tasks = self.data_ops_javasdk_loader_in_batches(
                    sdk_data_loader=gen_create,
                    batch_size=10**4,
                    dataset=self.json_template
                )
                for task in tasks:
                    task.result()
                self.log.info(
                    f"[STEP 6.a] PASSED - Loaded {self.num_of_docs_per_collection} documents into each bucket: {bucket_names}"
                )
            except Exception as e:
                self.log.error(f"[STEP 6.a] FAILED - Document loading failed: {str(e)}")
                raise

            for idx, bucket_name in enumerate(bucket_names):
                self.log.info(f"[STEP 6.{idx+1}] Processing bucket '{bucket_name}'...")
                namespace = f"default:{bucket_name}._default._default"

                # Step 6b: Create indexes and collect select queries
                try:
                    self.log.info(f"[STEP 6.{idx+1}.b] Creating indexes on '{bucket_name}'...")
                    prefix = 'ear_' + ''.join(random.choices(string.ascii_letters + string.digits, k=5))
                    query_definitions = self.gsi_util_obj.get_index_definition_list(
                        dataset=self.json_template,
                        prefix=prefix,
                        skip_primary=False
                    )
                    self.log.info(f"[STEP 5.{idx+1}.b] Generated {len(query_definitions)} index definitions with prefix '{prefix}'")
                    
                    # Collect select queries for validation
                    select_queries.update(
                        self.gsi_util_obj.get_select_queries(
                            definition_list=query_definitions,
                            namespace=namespace
                        )
                    )
                    
                    deploy_nodes = [f"{node.ip}:{self.node_port}" for node in index_nodes]
                    queries = self.gsi_util_obj.get_create_index_list(
                        definition_list=query_definitions,
                        namespace=namespace,
                        num_replica=self.num_index_replica,
                        deploy_node_info=deploy_nodes,
                        defer_build=self.defer_build
                    )
                    self.log.info(f"[STEP 6.{idx+1}.b] Generated {len(queries)} CREATE INDEX queries")
                    
                    query_node = self.get_nodes_from_services_map(service_type="n1ql")
                    self.gsi_util_obj.create_gsi_indexes(
                        create_queries=queries,
                        database=namespace,
                        query_node=query_node
                    )
                    self.log.info(f"[STEP 6.{idx+1}.b] PASSED - Created indexes on '{bucket_name}'")
                except Exception as e:
                    self.log.error(f"[STEP 6.{idx+1}.b] FAILED - Index creation failed for '{bucket_name}': {str(e)}")
                    raise
            
            self.log.info(f"[STEP 6] PASSED - Document loading and index creation completed for all buckets. Collected {len(select_queries)} select queries")
        except Exception as e:
            self.log.error(f"[STEP 6] FAILED - Document loading/index creation failed: {str(e)}")
            raise
        
        # ========== STEP 7: Wait for indexes to be online ==========
        try:
            self.log.info("[STEP 7] Waiting for all indexes to reach 'Ready' state...")
            self.wait_until_indexes_online(timeout=1200, defer_build=self.defer_build)
            self.log.info("[STEP 7] PASSED - All indexes are in 'Ready' state")
        except Exception as e:
            self.log.error(f"[STEP 7] FAILED - Index online wait failed: {str(e)}")
            raise
        
        # ========== STEP 8: Run SELECT queries and validate results ==========
        try:
            self.log.info(f"[STEP 8] Running {len(select_queries)} SELECT queries for all indexes after encryption...")
            
            # Capture scan stats before queries
            stats_before = self._capture_scan_stats()
            
            # Run and validate all select queries
            self._run_and_validate_scans(select_queries, expected_doc_count=self.num_of_docs_per_collection)
            
            # Validate scan stats increased
            self._validate_scan_stats_increment(stats_before)
            
            self.log.info(f"[STEP 8] PASSED - All {len(select_queries)} SELECT queries executed successfully with encryption enabled")
        except Exception as e:
            self.log.error(f"[STEP 8] FAILED - SELECT query validation failed: {str(e)}")
            raise
        
        # ========== STEP 9: Validate item counts and related validations ==========
        try:
            self.log.info("[STEP 9] Running item count related validations (KV vs GSI, replica counts, pending mutations)...")
            self.item_count_related_validations()
            self.log.info("[STEP 9] PASSED - Item count related validations completed successfully")
        except Exception as e:
            self.log.error(f"[STEP 9] FAILED - Item count validation failed: {str(e)}")
            raise
        
        # ========== STEP 10: Validate file encryption on disk ==========
        try:
            expected_header_key_ids = self._get_indexer_in_use_key_ids(index_nodes)
            self.log.info(
                f"[STEP 10] Validating file encryption on disk and checking for "
                f"in-use key ids {expected_header_key_ids} in encrypted file headers for "
                f"encrypted buckets: {encrypted_bucket_names}..."
            )
            encryption_results = self.validate_file_encryption(
                index_nodes,
                expected_key_id=expected_header_key_ids,
                encrypted_bucket_names=encrypted_bucket_names
            )
            
            # Track overall validation status
            all_failed_files = []
            validation_passed = True
            
            # Log summary of results
            for category, results in encryption_results.items():
                if category == "TODO":
                    continue
                if isinstance(results, dict):
                    for node, result in results.items():
                        status = result.get("status", "unknown")
                        if status == "passed":
                            # Check if there are any failed files even in passed results
                            failed_files = result.get("failed_files", [])
                            if failed_files:
                                self.log.warning(f"[STEP 10] {category} on {node}: PASSED with {len(failed_files)} unencrypted files")
                                for file_path, details in failed_files:
                                    self.log.error(f"[STEP 10] UNENCRYPTED FILE on {node}: {file_path} - {details}")
                                    all_failed_files.append((node, file_path, details))
                            else:
                                self.log.info(f"[STEP 10] {category} on {node}: PASSED - All files encrypted")
                        elif status == "failed":
                            validation_passed = False
                            self.log.error(f"[STEP 10] {category} on {node}: FAILED - {result.get('reason', 'unknown')}")
                            # Explicitly list all failed files
                            failed_files = result.get("failed_files", [])
                            if failed_files:
                                self.log.error(f"[STEP 10] === UNENCRYPTED FILES on {node} ({len(failed_files)} files) ===")
                                for file_path, details in failed_files:
                                    self.log.error(f"[STEP 10] UNENCRYPTED FILE: {file_path}")
                                    self.log.error(f"[STEP 10]   Details: {details}")
                                    all_failed_files.append((node, file_path, details))
                        elif status == "skipped":
                            self.log.warning(f"[STEP 10] {category} on {node}: SKIPPED - {result.get('reason', 'unknown')}")
            
            # Final summary of all unencrypted files
            if all_failed_files:
                self.log.error("=" * 60)
                self.log.error(f"[STEP 10] SUMMARY: Found {len(all_failed_files)} UNENCRYPTED FILES:")
                for node, file_path, details in all_failed_files:
                    self.log.error(f"[STEP 10]   Node: {node}, File: {file_path}")
                self.log.error("=" * 60)
                raise Exception(f"File encryption validation failed: {len(all_failed_files)} files are not encrypted")

            if not validation_passed:
                raise Exception("File encryption validation reported one or more failures")
            
            self.log.info("[STEP 10] PASSED - File encryption validation completed successfully")
        except Exception as e:
            self.log.error(f"[STEP 10] FAILED - File encryption validation failed: {str(e)}")
            raise
        
        # ========== TEST COMPLETE ==========
        self.log.info("=" * 80)
        self.log.info("TEST PASSED: test_gsi_encryption_at_rest_sanity")
        self.log.info(f"Test completed successfully with gsi_type={self.gsi_type}")
        self.log.info("=" * 80)

    def test_gsi_encryption_at_rest_key_rotation(self):
        """
        Encryption at rest key rotation test.
        
        Test validates:
        1. Initial encryption setup with key1 (from basetestcase.py)
        2. Create bucket with encryption enabled using key1
        3. Create indexes and load documents
        4. Run baseline validations with key1
        5. Create new encryption key (key2)
        6. Rotate bucket encryption to key2
        7. Wait for rotation to complete and snapshots to be created with new key
        8. Rerun validations to verify files are encrypted with key2
        
        This test ensures that after key rotation:
        - New snapshot files are encrypted with the new key
        - GSI operations continue to work correctly
        - File headers contain the new key ID
        """
        self.log.info("=" * 80)
        self.log.info("STARTING TEST: test_gsi_encryption_at_rest_key_rotation")
        self.log.info(f"Test parameters: gsi_type={self.gsi_type}")
        self.log.info("=" * 80)
        
        # ========== STEP 1: Verify prerequisites ==========
        try:
            self.log.info("[STEP 1] Verifying prerequisites...")
            
            # Check index nodes
            index_nodes = self.get_nodes_from_services_map(service_type="index", get_all_nodes=True)
            self.log.info(f"[STEP 1] Found {len(index_nodes)} index nodes")
            self.assertGreaterEqual(len(index_nodes), 2, f"Need at least 2 index nodes, found {len(index_nodes)}")
            
            # Check encryption at rest is enabled
            if not self.enable_encryption_at_rest:
                self.skipTest("Encryption at rest not enabled. Set enable_encryption_at_rest=True")
            
            # Save the initial key ID (key1)
            key1_id = self.encryption_at_rest_id
            self.log.info(f"[STEP 1] Initial encryption key ID (key1): {key1_id}")
            self.assertIsNotNone(key1_id, "Initial encryption_at_rest_id is None")
            
            self.log.info("[STEP 1] PASSED - Prerequisites verified")
        except Exception as e:
            self.log.error(f"[STEP 1] FAILED: {str(e)}")
            raise
        
        # ========== STEP 2: Set indexer snapshot settings ==========
        try:
            self.log.info("[STEP 2] Setting indexer snapshot settings...")
            for index_node in index_nodes:
                rest = RestConnection(index_node)
                rest.set_index_settings({"indexer.settings.persisted_snapshot.moi.interval": 60000})
                rest.set_index_settings({"indexer.settings.persisted_snapshot_init_build.moi.interval": 60000})
            self.log.info("[STEP 2] PASSED - Indexer snapshot settings configured")
        except Exception as e:
            self.log.error(f"[STEP 2] FAILED: {str(e)}")
            raise
        
        # ========== STEP 3: Create bucket with encryption using key1 ==========
        bucket_name = self.test_bucket
        try:
            self.log.info(f"[STEP 3] Creating bucket '{bucket_name}' with encryption key1 ({key1_id})...")
            self._create_bucket_with_encryption(bucket_name, enable_encryption=True)
            
            # Verify bucket encryption
            bucket_info = self.rest.get_bucket_json(bucket_name)
            encryption_key_id = bucket_info.get('encryptionAtRestKeyId', None)
            self.assertEqual(encryption_key_id, key1_id, 
                f"Bucket encryption key {encryption_key_id} does not match key1 {key1_id}")
            
            self.log.info(f"[STEP 3] PASSED - Bucket created with encryption key1")
        except Exception as e:
            self.log.error(f"[STEP 3] FAILED: {str(e)}")
            raise
        
        # ========== STEP 4: Load documents ==========
        try:
            self.log.info(f"[STEP 4] Loading {self.num_of_docs_per_collection} documents...")
            gen_create = SDKDataLoader(
                num_ops=self.num_of_docs_per_collection,
                percent_create=100,
                percent_update=0,
                percent_delete=0,
                scope="_default",
                collection="_default",
                json_template=self.json_template,
                output=True,
                username=self.username,
                password=self.password
            )
            tasks = self.data_ops_javasdk_loader_in_batches(
                sdk_data_loader=gen_create,
                batch_size=10**4,
                dataset=self.json_template
            )
            for task in tasks:
                task.result()
            self.log.info(f"[STEP 4] PASSED - Loaded {self.num_of_docs_per_collection} documents")
        except Exception as e:
            self.log.error(f"[STEP 4] FAILED: {str(e)}")
            raise
        
        # ========== STEP 5: Create indexes ==========
        namespace = f"default:{bucket_name}._default._default"
        select_queries = set()
        try:
            self.log.info(f"[STEP 5] Creating indexes...")
            prefix = 'rotation_' + ''.join(random.choices(string.ascii_letters + string.digits, k=5))
            query_definitions = self.gsi_util_obj.get_index_definition_list(
                dataset=self.json_template,
                prefix=prefix,
                skip_primary=False
            )
            
            select_queries.update(
                self.gsi_util_obj.get_select_queries(
                    definition_list=query_definitions,
                    namespace=namespace
                )
            )
            
            deploy_nodes = [f"{node.ip}:{self.node_port}" for node in index_nodes]
            queries = self.gsi_util_obj.get_create_index_list(
                definition_list=query_definitions,
                namespace=namespace,
                num_replica=self.num_index_replica,
                deploy_node_info=deploy_nodes,
                defer_build=self.defer_build
            )
            
            query_node = self.get_nodes_from_services_map(service_type="n1ql")
            self.gsi_util_obj.create_gsi_indexes(
                create_queries=queries,
                database=namespace,
                query_node=query_node
            )
            self.log.info(f"[STEP 5] PASSED - Created {len(queries)} indexes")
        except Exception as e:
            self.log.error(f"[STEP 5] FAILED: {str(e)}")
            raise
        
        # ========== STEP 6: Wait for indexes to be online ==========
        try:
            self.log.info("[STEP 6] Waiting for indexes to be online...")
            self.wait_until_indexes_online(timeout=1200, defer_build=self.defer_build)
            self.log.info("[STEP 6] PASSED - All indexes online")
        except Exception as e:
            self.log.error(f"[STEP 6] FAILED: {str(e)}")
            raise

        baseline_in_use_key_ids = self._get_indexer_in_use_key_ids(index_nodes)
        
        # ========== STEP 7: Run baseline validations with key1 ==========
        try:
            self.log.info("[STEP 7] Running baseline validations with key1...")
            
            # Run scan queries
            stats_before = self._capture_scan_stats()
            self._run_and_validate_scans(select_queries, expected_doc_count=self.num_of_docs_per_collection)
            self._validate_scan_stats_increment(stats_before)
            
            # Validate item counts
            self.item_count_related_validations()
            
            # Validate file encryption with key1
            validation_passed = self._validate_file_encryption_with_key(
                index_nodes, expected_key_id=baseline_in_use_key_ids, step_prefix="[STEP 7] "
            )
            if not validation_passed:
                raise Exception("Baseline file encryption validation failed with key1")
            
            self.log.info("[STEP 7] PASSED - Baseline validations completed with key1")
        except Exception as e:
            self.log.error(f"[STEP 7] FAILED: {str(e)}")
            raise
        
        # ========== STEP 8: Create new encryption key (key2) ==========
        try:
            self.log.info("[STEP 8] Creating new encryption key (key2)...")
            key2_id = self._create_new_encryption_key()
            self.log.info(f"[STEP 8] PASSED - Created key2 with ID: {key2_id}")
        except Exception as e:
            self.log.error(f"[STEP 8] FAILED: {str(e)}")
            raise
        
        # ========== STEP 9: Configure DEK rotation ==========
        try:
            self.log.info(f"[STEP 9] Configuring DEK rotation for bucket '{bucket_name}'...")
            self._rotate_bucket_encryption_key(bucket_name, key2_id, dek_rotation_interval=120, dek_lifetime=120)
            self.log.info(f"[STEP 9] PASSED - DEK rotation configured")
        except Exception as e:
            self.log.error(f"[STEP 9] FAILED: {str(e)}")
            raise
        
        # ========== STEP 10: Wait for DEK rotation and run mutations ==========
        try:
            self.log.info("[STEP 10] Waiting 120 seconds for DEK rotation to take effect...")
            self.sleep(120, "Waiting for DEK rotation interval")
            
            # Perform mutations to trigger new snapshot creation with rotated DEK
            self.log.info("[STEP 10] Running mutations to trigger snapshot creation with new DEK...")
            gen_update = SDKDataLoader(
                num_ops=1000,
                percent_create=0,
                percent_update=100,
                percent_delete=0,
                scope="_default",
                collection="_default",
                json_template=self.json_template,
                output=True,
                username=self.username,
                password=self.password
            )
            tasks = self.data_ops_javasdk_loader_in_batches(
                sdk_data_loader=gen_update,
                batch_size=1000,
                dataset=self.json_template
            )
            for task in tasks:
                task.result()
            
            # Wait for snapshots to be created with new DEK
            self.sleep(120, "Waiting for new snapshots to be created with key2")

            new_in_use_key_ids = self._get_new_indexer_in_use_key_ids(index_nodes, baseline_in_use_key_ids)
            if not new_in_use_key_ids:
                raise Exception("Indexer GetInUseKeys did not report any new key IDs after key rotation")
            
            self.log.info("[STEP 10] PASSED - Key rotation wait completed")
        except Exception as e:
            self.log.error(f"[STEP 10] FAILED: {str(e)}")
            raise
        
        # ========== STEP 11: Rerun validations with key2 ==========
        try:
            self.log.info("[STEP 11] Rerunning validations after key rotation...")
            
            # Run scan queries again
            stats_before = self._capture_scan_stats()
            self._run_and_validate_scans(select_queries, expected_doc_count=self.num_of_docs_per_collection)
            self._validate_scan_stats_increment(stats_before)
            
            # Validate item counts
            self.item_count_related_validations()
            
            # Validate file encryption with key2
            validation_passed = self._validate_file_encryption_with_key(
                index_nodes, expected_key_id=new_in_use_key_ids, step_prefix="[STEP 11] "
            )
            if not validation_passed:
                raise Exception("File encryption validation failed after key rotation to key2")
            
            self.log.info("[STEP 11] PASSED - Post-rotation validations completed with key2")
        except Exception as e:
            self.log.error(f"[STEP 11] FAILED: {str(e)}")
            raise
        
        # ========== TEST COMPLETE ==========
        self.log.info("=" * 80)
        self.log.info("TEST PASSED: test_gsi_encryption_at_rest_key_rotation")
        self.log.info(f"Successfully rotated encryption from key1 ({key1_id}) to key2 ({key2_id})")
        self.log.info("=" * 80)

    def test_gsi_encryption_at_rest_force_reencryption(self):
        """
        Encryption at rest force re-encryption test.
        
        This test validates the force re-encryption operation which:
        1. Drops all existing DEKs (Data Encryption Keys) for the bucket
        2. Creates new DEKs
        3. Re-encrypts ALL data in the bucket with the new DEKs
        4. The KEK (Key Encryption Key) ID stays the same - only DEKs change
        
        Test flow:
        1. Create bucket with encryption enabled
        2. Create indexes and load documents
        3. Run baseline validations
        4. Trigger force re-encryption (drop DEKs and re-encrypt)
        5. Wait for re-encryption to complete
        6. Rerun validations to verify data is still accessible and encrypted
        
        Use case: When DEKs may have been compromised and need to be replaced
        """
        self.log.info("=" * 80)
        self.log.info("STARTING TEST: test_gsi_encryption_at_rest_force_reencryption")
        self.log.info(f"Test parameters: gsi_type={self.gsi_type}")
        self.log.info("=" * 80)
        
        # ========== STEP 1: Verify prerequisites ==========
        try:
            self.log.info("[STEP 1] Verifying prerequisites...")
            
            index_nodes = self.get_nodes_from_services_map(service_type="index", get_all_nodes=True)
            self.log.info(f"[STEP 1] Found {len(index_nodes)} index nodes")
            self.assertGreaterEqual(len(index_nodes), 2, f"Need at least 2 index nodes, found {len(index_nodes)}")
            
            if not self.enable_encryption_at_rest:
                self.skipTest("Encryption at rest not enabled. Set enable_encryption_at_rest=True")
            
            key_id = self.encryption_at_rest_id
            self.log.info(f"[STEP 1] Encryption key ID: {key_id}")
            self.assertIsNotNone(key_id, "encryption_at_rest_id is None")
            
            self.log.info("[STEP 1] PASSED - Prerequisites verified")
        except Exception as e:
            self.log.error(f"[STEP 1] FAILED: {str(e)}")
            raise
        
        # ========== STEP 2: Set indexer snapshot settings ==========
        try:
            self.log.info("[STEP 2] Setting indexer snapshot settings...")
            for index_node in index_nodes:
                rest = RestConnection(index_node)
                rest.set_index_settings({"indexer.settings.persisted_snapshot.moi.interval": 60000})
                rest.set_index_settings({"indexer.settings.persisted_snapshot_init_build.moi.interval": 60000})
            self.log.info("[STEP 2] PASSED - Indexer snapshot settings configured")
        except Exception as e:
            self.log.error(f"[STEP 2] FAILED: {str(e)}")
            raise
        
        # ========== STEP 3: Create bucket with encryption ==========
        bucket_name = self.test_bucket
        try:
            self.log.info(f"[STEP 3] Creating bucket '{bucket_name}' with encryption...")
            self._create_bucket_with_encryption(bucket_name, enable_encryption=True)
            
            bucket_info = self.rest.get_bucket_json(bucket_name)
            encryption_key_id = bucket_info.get('encryptionAtRestKeyId', None)
            self.assertEqual(encryption_key_id, key_id, 
                f"Bucket encryption key {encryption_key_id} does not match {key_id}")
            
            self.log.info(f"[STEP 3] PASSED - Bucket created with encryption")
        except Exception as e:
            self.log.error(f"[STEP 3] FAILED: {str(e)}")
            raise
        
        # ========== STEP 4: Load documents ==========
        try:
            self.log.info(f"[STEP 4] Loading {self.num_of_docs_per_collection} documents...")
            gen_create = SDKDataLoader(
                num_ops=self.num_of_docs_per_collection,
                percent_create=100,
                percent_update=0,
                percent_delete=0,
                scope="_default",
                collection="_default",
                json_template=self.json_template,
                output=True,
                username=self.username,
                password=self.password
            )
            tasks = self.data_ops_javasdk_loader_in_batches(
                sdk_data_loader=gen_create,
                batch_size=10**4,
                dataset=self.json_template
            )
            for task in tasks:
                task.result()
            self.log.info(f"[STEP 4] PASSED - Loaded {self.num_of_docs_per_collection} documents")
        except Exception as e:
            self.log.error(f"[STEP 4] FAILED: {str(e)}")
            raise
        
        # ========== STEP 5: Create indexes ==========
        namespace = f"default:{bucket_name}._default._default"
        select_queries = set()
        try:
            self.log.info(f"[STEP 5] Creating indexes...")
            prefix = 'reencrypt_' + ''.join(random.choices(string.ascii_letters + string.digits, k=5))
            query_definitions = self.gsi_util_obj.get_index_definition_list(
                dataset=self.json_template,
                prefix=prefix,
                skip_primary=False
            )
            
            select_queries.update(
                self.gsi_util_obj.get_select_queries(
                    definition_list=query_definitions,
                    namespace=namespace
                )
            )
            
            deploy_nodes = [f"{node.ip}:{self.node_port}" for node in index_nodes]
            queries = self.gsi_util_obj.get_create_index_list(
                definition_list=query_definitions,
                namespace=namespace,
                num_replica=self.num_index_replica,
                deploy_node_info=deploy_nodes,
                defer_build=self.defer_build
            )
            
            query_node = self.get_nodes_from_services_map(service_type="n1ql")
            self.gsi_util_obj.create_gsi_indexes(
                create_queries=queries,
                database=namespace,
                query_node=query_node
            )
            self.log.info(f"[STEP 5] PASSED - Created {len(queries)} indexes")
        except Exception as e:
            self.log.error(f"[STEP 5] FAILED: {str(e)}")
            raise
        
        # ========== STEP 6: Wait for indexes to be online ==========
        try:
            self.log.info("[STEP 6] Waiting for indexes to be online...")
            self.wait_until_indexes_online(timeout=1200, defer_build=self.defer_build)
            self.log.info("[STEP 6] PASSED - All indexes online")
        except Exception as e:
            self.log.error(f"[STEP 6] FAILED: {str(e)}")
            raise

        baseline_in_use_key_ids = self._get_indexer_in_use_key_ids(index_nodes)
        
        # ========== STEP 7: Run baseline validations ==========
        try:
            self.log.info("[STEP 7] Running baseline validations before re-encryption...")
            
            stats_before = self._capture_scan_stats()
            self._run_and_validate_scans(select_queries, expected_doc_count=self.num_of_docs_per_collection)
            self._validate_scan_stats_increment(stats_before)
            
            self.item_count_related_validations()
            
            validation_passed = self._validate_file_encryption_with_key(
                index_nodes, expected_key_id=baseline_in_use_key_ids, step_prefix="[STEP 7] "
            )
            if not validation_passed:
                raise Exception("Baseline file encryption validation failed")
            
            self.log.info("[STEP 7] PASSED - Baseline validations completed")
        except Exception as e:
            self.log.error(f"[STEP 7] FAILED: {str(e)}")
            raise
        
        # ========== STEP 8: Capture DEK info before re-encryption ==========
        try:
            self.log.info("[STEP 8] Capturing DEK info before re-encryption...")
            bucket_info_before = self.rest.get_bucket_json(bucket_name)
            dek_info_before = bucket_info_before.get('encryptionAtRestInfo', {})
            dek_count_before = dek_info_before.get('dekNumber', 0)
            oldest_dek_before = dek_info_before.get('oldestDekCreationDatetime', None)
            
            self.log.info(f"[STEP 8] DEK count before: {dek_count_before}")
            self.log.info(f"[STEP 8] Oldest DEK creation time before: {oldest_dek_before}")
            self.log.info("[STEP 8] PASSED - DEK info captured")
        except Exception as e:
            self.log.error(f"[STEP 8] FAILED: {str(e)}")
            raise
        
        # ========== STEP 9: Trigger force re-encryption ==========
        try:
            self.log.info(f"[STEP 9] Triggering force re-encryption on bucket '{bucket_name}'...")
            self.log.info("[STEP 9] This will drop existing DEKs and re-encrypt all data with new DEKs")
            
            status, response = self.rest.trigger_data_reencryption(bucket_name)
            if not status:
                raise Exception(f"Failed to trigger re-encryption: {response}")
            
            self.log.info(f"[STEP 9] Force re-encryption triggered. Response: {response}")
            self.log.info("[STEP 9] PASSED - Re-encryption initiated")
        except Exception as e:
            self.log.error(f"[STEP 9] FAILED: {str(e)}")
            raise
        
        # ========== STEP 10: Wait for re-encryption to complete ==========
        try:
            self.log.info("[STEP 10] Waiting for re-encryption to complete...")
            
            # Wait and check encryption status
            max_wait_time = 300  # 5 minutes max
            wait_interval = 30
            total_waited = 0
            reencryption_complete = False
            
            while total_waited < max_wait_time:
                self.sleep(wait_interval, f"Waiting for re-encryption... ({total_waited + wait_interval}s/{max_wait_time}s)")
                total_waited += wait_interval
                
                bucket_info = self.rest.get_bucket_json(bucket_name)
                enc_info = bucket_info.get('encryptionAtRestInfo', {})
                data_status = enc_info.get('dataStatus', '')
                issues = enc_info.get('issues', [])
                
                self.log.info(f"[STEP 10] Data status: {data_status}, Issues: {issues}")
                
                if data_status == 'encrypted' and not issues:
                    reencryption_complete = True
                    break
            
            if not reencryption_complete:
                self.log.warning(f"[STEP 10] Re-encryption may not be fully complete after {max_wait_time}s")

            new_in_use_key_ids = self._get_new_indexer_in_use_key_ids(index_nodes, baseline_in_use_key_ids)
            if not new_in_use_key_ids:
                raise Exception("Indexer GetInUseKeys did not report any new key IDs after re-encryption")
            
            self.log.info("[STEP 10] PASSED - Re-encryption wait completed")
        except Exception as e:
            self.log.error(f"[STEP 10] FAILED: {str(e)}")
            raise
        
        # ========== STEP 11: Verify DEK info changed ==========
        try:
            self.log.info("[STEP 11] Verifying DEK info changed after re-encryption...")
            bucket_info_after = self.rest.get_bucket_json(bucket_name)
            dek_info_after = bucket_info_after.get('encryptionAtRestInfo', {})
            dek_count_after = dek_info_after.get('dekNumber', 0)
            oldest_dek_after = dek_info_after.get('oldestDekCreationDatetime', None)
            
            self.log.info(f"[STEP 11] DEK count after: {dek_count_after}")
            self.log.info(f"[STEP 11] Oldest DEK creation time after: {oldest_dek_after}")
            
            # Verify KEK ID stayed the same
            encryption_key_id_after = bucket_info_after.get('encryptionAtRestKeyId', None)
            self.assertEqual(encryption_key_id_after, key_id, 
                f"KEK ID changed unexpectedly from {key_id} to {encryption_key_id_after}")
            self.log.info(f"[STEP 11] KEK ID unchanged: {key_id}")
            
            # Verify oldest DEK creation time changed (new DEKs were created)
            if oldest_dek_before and oldest_dek_after:
                if oldest_dek_after != oldest_dek_before:
                    self.log.info(f"[STEP 11] DEKs were rotated - oldest DEK changed from {oldest_dek_before} to {oldest_dek_after}")
                else:
                    self.log.warning(f"[STEP 11] Oldest DEK timestamp unchanged - re-encryption may still be in progress")
            
            self.log.info("[STEP 11] PASSED - DEK info verification completed")
        except Exception as e:
            self.log.error(f"[STEP 11] FAILED: {str(e)}")
            raise
        
        # ========== STEP 12: Rerun validations after re-encryption ==========
        try:
            self.log.info("[STEP 12] Rerunning validations after re-encryption...")
            
            # Run scan queries again
            stats_before = self._capture_scan_stats()
            self._run_and_validate_scans(select_queries, expected_doc_count=self.num_of_docs_per_collection)
            self._validate_scan_stats_increment(stats_before)
            
            # Validate item counts
            self.item_count_related_validations()
            
            validation_passed = self._validate_file_encryption_with_key(
                index_nodes, expected_key_id=new_in_use_key_ids, step_prefix="[STEP 12] "
            )
            if not validation_passed:
                raise Exception("File encryption validation failed after re-encryption")
            
            self.log.info("[STEP 12] PASSED - Post-reencryption validations completed")
        except Exception as e:
            self.log.error(f"[STEP 12] FAILED: {str(e)}")
            raise
        
        # ========== TEST COMPLETE ==========
        self.log.info("=" * 80)
        self.log.info("TEST PASSED: test_gsi_encryption_at_rest_force_reencryption")
        self.log.info(f"Successfully dropped DEKs and re-encrypted data with new DEKs (KEK ID: {key_id})")
        self.log.info("=" * 80)
