-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 09:22:54 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema flightstats
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `flightstats` ;

-- -----------------------------------------------------
-- Schema flightstats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flightstats` DEFAULT CHARACTER SET latin1 ;
USE `flightstats` ;

-- -----------------------------------------------------
-- Table `flightstats`.`aircraft`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flightstats`.`aircraft` ;

CREATE TABLE IF NOT EXISTS `flightstats`.`aircraft` (
  `tail_num` VARCHAR(100) NOT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`tail_num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `flightstats`.`aircraft_engines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flightstats`.`aircraft_engines` ;

CREATE TABLE IF NOT EXISTS `flightstats`.`aircraft_engines` (
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `aircraft_engine_code` VARCHAR(45) NOT NULL DEFAULT 'default',
  `manufacturer` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`aircraft_engine_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `flightstats`.`airport_remarks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flightstats`.`airport_remarks` ;

CREATE TABLE IF NOT EXISTS `flightstats`.`airport_remarks` (
  `code` VARCHAR(100) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `site_number` INT(11) NOT NULL,
  `airport_remark_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`site_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `flightstats`.`airports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flightstats`.`airports` ;

CREATE TABLE IF NOT EXISTS `flightstats`.`airports` (
  `code` VARCHAR(100) NOT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `longitude` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `flightstats`.`carriers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flightstats`.`carriers` ;

CREATE TABLE IF NOT EXISTS `flightstats`.`carriers` (
  `code` VARCHAR(100) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `longitude` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `flightstats`.`ontime_mysiam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flightstats`.`ontime_mysiam` ;

CREATE TABLE IF NOT EXISTS `flightstats`.`ontime_mysiam` (
  `carrier` VARCHAR(100) NULL DEFAULT NULL,
  `origin_destination` VARCHAR(45) NULL DEFAULT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `tail_num` VARCHAR(100) NULL DEFAULT NULL,
  `origin` VARCHAR(45) NULL DEFAULT NULL,
  `destination` VARCHAR(45) NULL DEFAULT NULL,
  `id` VARCHAR(45) NOT NULL DEFAULT '"default"',
  `dep_time` VARCHAR(45) NULL DEFAULT NULL,
  `distance` INT(11) NULL DEFAULT NULL,
  `aircraft_engine_code` VARCHAR(45) NULL DEFAULT NULL,
  `site_number` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `flightstats`.`states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flightstats`.`states` ;

CREATE TABLE IF NOT EXISTS `flightstats`.`states` (
  `state_code` VARCHAR(100) NOT NULL,
  `code` VARCHAR(100) NULL DEFAULT NULL,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`state_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `flightstats`.`zipcodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flightstats`.`zipcodes` ;

CREATE TABLE IF NOT EXISTS `flightstats`.`zipcodes` (
  `state_code` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `zipcode` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`state_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
