SELECT h.name, (SELECT COUNT(*) FROM bookings WHERE hotel_id = h.hotel_id) AS booking_count FROM hotel AS h WHERE h.city = "New York";
SELECT h.name, AVG(rv.ratings.Overall) AS average_rating FROM hotel AS h JOIN reviews AS rv ON h.hotel_id = rv.hotel_id GROUP BY h.name;
SELECT u.name, AVG(rv.ratings.Rooms) AS avg_room_rating FROM users AS u JOIN reviews AS rv ON u.user_id = rv.user_id WHERE rv.hotel_id = "hotel123" GROUP BY u.name;
SELECT h.name, h.city, COUNT(b.booking_id) AS total_bookings FROM hotel AS h JOIN bookings AS b ON h.hotel_id = b.hotel_id WHERE h.country = "USA" GROUP BY h.name, h.city;
SELECT h.name, MIN(rt.price) AS min_price FROM hotel AS h UNNEST h.room_types AS rt WHERE h.city = "New York" GROUP BY h.name;
SELECT rv.hotel_id, COUNT(rv.review_id) AS total_reviews FROM (SELECT review_id, hotel_id FROM reviews WHERE review_date > "2023-10-01") AS rv GROUP BY rv.hotel_id;
SELECT h.country, AVG(h.rating) AS avg_hotel_rating FROM hotel AS h WHERE h.free_wifi = TRUE GROUP BY h.country;
SELECT h.email, SUM(rt.availability) AS total_rooms FROM hotel AS h UNNEST h.room_types AS rt WHERE h.free_parking = TRUE GROUP BY h.email;
SELECT user_id, (SELECT COUNT(*) FROM bookings WHERE bookings.user_id = u.user_id) AS bookings_count FROM users AS u;
SELECT b.hotel_id, SUM(b.total_price) AS total_revenue FROM bookings AS b JOIN hotel AS h ON b.hotel_id = h.hotel_id WHERE h.city = "New York" GROUP BY b.hotel_id;
SELECT DISTINCT h.country, (SELECT COUNT(*) FROM hotel WHERE hotel.country = h.country) AS hotel_count FROM hotel AS h;
SELECT u.user_id, u.name, COUNT(b.booking_id) AS bookings_made FROM users AS u JOIN bookings AS b ON u.user_id = b.user_id WHERE b.payment_status = "Paid" GROUP BY u.user_id, u.name;
SELECT h.hotel_id, MAX(b.total_price) AS highest_booking_value FROM hotel AS h JOIN bookings AS b ON h.hotel_id = b.hotel_id GROUP BY h.hotel_id;
SELECT h.city, SUM(h.rooms) AS total_city_rooms FROM hotel AS h GROUP BY h.city;
SELECT h.name, MIN(rt.price) AS min_room_price FROM hotel AS h UNNEST h.room_types AS rt GROUP BY h.name;
SELECT b.hotel_id, COUNT(DISTINCT b.user_id) AS unique_users FROM bookings AS b GROUP BY b.hotel_id;
SELECT h.city, COUNT(h.hotel_id) AS total_hotels FROM hotel AS h GROUP BY h.city;
SELECT u.country, SUM(b.total_price) AS total_spent FROM users AS u JOIN bookings AS b ON u.user_id = b.user_id WHERE b.payment_status = "Paid" GROUP BY u.country;
SELECT h.hotel_id, (SELECT AVG(rt.price) FROM hotel UNNEST h.room_types AS rt) AS average_room_price FROM hotel AS h;
SELECT h.hotel_id, COUNT(rv.review_id) AS number_of_reviews FROM hotel AS h LEFT JOIN reviews AS rv ON h.hotel_id = rv.hotel_id GROUP BY h.hotel_id;
SELECT u.city, AVG(rv.ratings.Cleanliness) AS avg_cleanliness FROM users AS u JOIN reviews AS rv ON u.user_id = rv.user_id GROUP BY u.city;
SELECT h.city, COUNT(rv.review_id) AS reviews_per_city FROM hotel AS h LEFT JOIN reviews AS rv ON h.hotel_id = rv.hotel_id GROUP BY h.city;
SELECT u.country, COUNT(DISTINCT u.user_id) AS unique_travelers FROM users AS u JOIN bookings AS b ON u.user_id = b.user_id GROUP BY u.country;
SELECT h.hotel_id, (SELECT AVG(rt.price) FROM hotel UNNEST h.room_types AS rt) AS avg_price FROM hotel AS h WHERE h.rating > 4;
SELECT h.city, AVG(rt.price) AS average_price_of_room FROM hotel AS h UNNEST h.room_types AS rt GROUP BY h.city;
SELECT h.country, MAX(rv.ratings.Overall) AS highest_overall_rating FROM hotel AS h JOIN reviews AS rv ON h.hotel_id = rv.hotel_id GROUP BY h.country;
SELECT u.name, SUM(b.room_count) AS total_rooms_booked FROM users AS u JOIN bookings AS b ON u.user_id = b.user_id GROUP BY u.name;
SELECT h.type, COUNT(h.name) AS count_by_type FROM hotel AS h GROUP BY h.type;
SELECT h.hotel_id AS h_id, (SELECT AVG(rt.availability) FROM hotel UNNEST h.room_types AS rt) AS avg_avail FROM hotel AS h;
SELECT h.country, AVG(rt.price) AS avg_price FROM hotel AS h UNNEST h.room_types AS rt WHERE rt.availability > 0 GROUP BY h.country;
SELECT h.hotel_id, COUNT(DISTINCT rv.user_id) AS unique_reviewers FROM hotel AS h LEFT JOIN reviews AS rv ON h.hotel_id = rv.hotel_id GROUP BY h.hotel_id;
SELECT u.user_id, (SELECT COUNT(*) FROM bookings b WHERE b.user_id = u.user_id AND b.payment_status = "Paid") AS paid_bookings_count FROM users AS u;
SELECT h.hotel_id, (SELECT AVG(ratings.Rooms) FROM reviews WHERE hotel_id = h.hotel_id) AS avg_room_rating FROM hotel AS h;
SELECT b.payment_method, SUM(b.room_count) AS room_count_by_payment FROM bookings AS b GROUP BY b.payment_method;
SELECT h.hotel_id, (SELECT COUNT(*) FROM reviews WHERE hotel_id = h.hotel_id AND ratings.Overall = 5) AS five_star_reviews FROM hotel AS h;
SELECT h.city, AVG(rv.ratings.Cleanliness) AS cleanliness_in_city FROM hotel AS h JOIN reviews AS rv ON h.hotel_id = rv.hotel_id WHERE rv.ratings.Cleanliness > 3 GROUP BY h.city;
SELECT h.hotel_id, (SELECT SUM(b.total_price) FROM bookings AS b WHERE b.hotel_id = h.hotel_id) AS total_earnings FROM hotel AS h;
SELECT h.name, (SELECT COUNT(*) FROM reviews WHERE hotel_id = h.hotel_id) AS review_count FROM hotel AS h WHERE (SELECT COUNT(*) FROM reviews WHERE hotel_id = h.hotel_id) > 20;
SELECT h.name, MAX(b.total_price) AS max_price FROM bookings AS b JOIN hotel AS h ON h.hotel_id = b.hotel_id WHERE b.payment_status = "Paid" GROUP BY h.name;
SELECT h.hotel_id, AVG(rv.ratings.`Value`) AS avg_value_rating FROM hotel AS h JOIN reviews AS rv ON h.hotel_id = rv.hotel_id GROUP BY h.hotel_id;
SELECT u.user_id, u.name AS user_name, AVG(b.total_price) AS avg_spent FROM users u JOIN bookings b ON u.user_id = b.user_id GROUP BY u.user_id, u.name;
SELECT h.name AS hotel_name, COUNT(rv.review_id) AS total_revs FROM hotel AS h JOIN reviews AS rv ON h.hotel_id = rv.hotel_id GROUP BY h.name;
SELECT b.user_id, MAX(b.total_price) AS max_spent FROM bookings AS b GROUP BY b.user_id;
SELECT u.city AS user_city, COUNT(b.booking_id) AS total_user_bookings FROM users AS u JOIN bookings AS b ON u.user_id = b.user_id WHERE b.payment_status = "Paid" GROUP BY u.city;
SELECT h.name AS hotel_name, COUNT(b.booking_id) AS number_of_bookings FROM hotel AS h JOIN bookings AS b ON h.hotel_id = b.hotel_id WHERE b.checkin > "2023-10-01" GROUP BY h.name;
SELECT hotel_id, AVG(ratings.Overall) AS avg_rating FROM reviews WHERE review_date BETWEEN "2023-10-01" AND "2023-10-31" GROUP BY hotel_id;
SELECT h.city AS hotel_city, COUNT(DISTINCT b.user_id) AS uniq_users FROM hotel AS h JOIN bookings AS b ON h.hotel_id = b.hotel_id GROUP BY h.city;
SELECT u.country AS user_country, COUNT(b.booking_id) AS bookings_per_country FROM users u JOIN bookings b ON u.user_id = b.user_id GROUP BY u.country;
