SELECT h.name, (SELECT AVG(r.ratings.Overall) FROM reviews r WHERE r.hotel_id = h.hotel_id) AS avg_overall_rating FROM hotel h WHERE h.city = "New York";
SELECT b.booking_id, u.name, (SELECT COUNT(rb.review_id) FROM reviews rb WHERE rb.user_id = b.user_id) AS review_count FROM bookings b JOIN users u ON b.user_id = u.user_id;
SELECT h.name, (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.hotel_id = h.hotel_id) AS booking_count FROM hotel h WHERE h.rating > 4.0;
SELECT r.review_id, r.comments, (SELECT u.name FROM users u WHERE u.user_id = r.user_id) AS reviewer_name FROM reviews r WHERE r.ratings.Overall > 4;
SELECT h.name, (SELECT avg_price FROM (SELECT AVG(rt.price) AS avg_price FROM h.room_types rt) tmp) AS average_room_price FROM hotel h WHERE h.free_wifi = TRUE;
SELECT b.booking_id, b.total_price, (SELECT AVG(bi.total_price) FROM bookings bi WHERE bi.hotel_id = b.hotel_id) AS average_hotel_booking_price FROM bookings b WHERE b.payment_status = "Paid";
SELECT h.name, (SELECT AVG(r.ratings.Cleanliness) FROM reviews r WHERE r.hotel_id = h.hotel_id) AS avg_cleanliness FROM hotel h WHERE h.country = "USA";
SELECT u.username, (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.user_id = u.user_id) AS total_bookings FROM users u WHERE (SELECT COUNT(r.review_id) FROM reviews r WHERE r.user_id = u.user_id) > 5;
SELECT b.booking_id, (SELECT SUM(bt.total_price) FROM bookings bt WHERE bt.user_id = b.user_id) AS user_spending FROM bookings b WHERE b.checkin >= "2023-10-01T00:00:00";
SELECT b.booking_id, b.checkin, b.checkout, (SELECT h.rooms FROM hotel h WHERE h.hotel_id = b.hotel_id) AS total_rooms FROM bookings b WHERE b.room_count > 2;
SELECT h.name, (SELECT MIN(rt.price) FROM h.room_types rt) AS min_price, (SELECT MAX(rt.price) FROM h.room_types rt) AS max_price FROM hotel h WHERE h.free_parking = TRUE;
SELECT b.booking_id, (SELECT u.city FROM users u WHERE u.user_id = b.user_id) AS user_city FROM bookings b WHERE b.total_price > 500;
SELECT h.name, h.rating, (SELECT AVG(r.ratings.Overall) FROM reviews r WHERE r.hotel_id = h.hotel_id) AS avg_review_rating FROM hotel h WHERE h.city = "San Francisco";
SELECT b.booking_id, (SELECT COUNT(r.review_id) FROM reviews r WHERE r.hotel_id = b.hotel_id) AS hotel_reviews FROM bookings b WHERE b.checkin <= "2023-10-31T23:59:59";
SELECT h.name, (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.hotel_id = h.hotel_id AND b.payment_status = "Paid") AS total_paid_bookings FROM hotel h WHERE h.rating >= 4.5;
SELECT u.username, (SELECT SUM(b.total_price) / (SELECT COUNT(b2.booking_id) FROM bookings b2 WHERE b2.user_id = u.user_id) FROM bookings b WHERE b.user_id = u.user_id) AS avg_spending FROM users u WHERE u.country = "USA";
SELECT h.hotel_id, (SELECT COUNT(r.review_id) FROM reviews r WHERE r.hotel_id = h.hotel_id) AS total_reviews FROM hotel h WHERE (SELECT AVG(rt.price) FROM h.room_types rt) < 200;
SELECT r.comments, (SELECT u.username FROM users u WHERE u.user_id = r.user_id) AS user_handle FROM reviews r WHERE r.review_date > "2023-09-01T00:00:00";
SELECT h.name, (SELECT COUNT(h2.name) FROM hotel h2 WHERE h2.city = h.city AND h2.free_wifi = TRUE) AS wifi_enabled_hotels FROM hotel h WHERE h.city = "Toronto";
SELECT b.booking_id, (SELECT (rt.price * b.room_count) FROM hotel h UNNEST h.room_types rt WHERE rt.name = b.room_type AND h.hotel_id = b.hotel_id) AS calculated_price FROM bookings b WHERE b.payment_method = "Credit Card";
SELECT h.name, (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.hotel_id = h.hotel_id AND b.checkin >= "2023-12-01T00:00:00") AS future_bookings FROM hotel h WHERE h.rooms > 50;
SELECT r.review_id, (SELECT b.total_price FROM bookings b WHERE b.user_id = r.user_id AND b.hotel_id = r.hotel_id ORDER BY b.checkin DESC LIMIT 1) AS latest_booking_price FROM reviews r WHERE r.ratings.Overall = 5;
SELECT h.name, (SELECT COUNT(r.review_id) FROM reviews r WHERE r.hotel_id = h.hotel_id AND r.review_date >= "2023-01-01T00:00:00") AS yearly_reviews FROM hotel h WHERE h.type = "Resort";
SELECT b.booking_id, (SELECT SUM(bt.room_count) FROM bookings bt WHERE bt.hotel_id = b.hotel_id AND bt.checkin >= "2023-10-01T00:00:00") AS total_room_bookings FROM bookings b WHERE b.payment_status = "Pending";
SELECT h.name, (SELECT COUNT(DISTINCT u.country) FROM users u JOIN bookings b ON b.user_id = u.user_id WHERE b.hotel_id = h.hotel_id) AS unique_countries FROM hotel h WHERE h.city = "Dubai";
SELECT b.booking_id, (SELECT r.comments FROM reviews r WHERE r.user_id = b.user_id AND r.hotel_id = b.hotel_id LIMIT 1) AS user_review FROM bookings b WHERE b.total_price < 300;
SELECT h.name, (SELECT MIN(ratings.Overall) FROM reviews WHERE hotel_id = h.hotel_id) AS min_overall_rating FROM hotel h WHERE h.rating > 3.5;
SELECT r.review_id, (SELECT COUNT(ub.booking_id) FROM bookings ub WHERE ub.user_id = r.user_id) AS total_user_bookings FROM reviews r WHERE r.ratings.Rooms = 5;
SELECT b.booking_id, (SELECT COUNT(r.review_id) FROM reviews r WHERE r.user_id = b.user_id) AS count_user_reviews FROM bookings b WHERE b.payment_status = "Cancelled";
SELECT h.name, (SELECT AVG(b.total_price) FROM bookings b WHERE b.hotel_id = h.hotel_id) AS avg_hotel_income FROM hotel h WHERE h.free_parking = TRUE;
SELECT u.username, (SELECT COUNT(r.review_id) FROM reviews r WHERE r.user_id = u.user_id) AS review_count FROM users u WHERE (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.user_id = u.user_id) > 10;
SELECT h.name, (SELECT COUNT(*) FROM reviews r WHERE r.hotel_id = h.hotel_id AND r.review_date BETWEEN "2023-01-01T00:00:00" AND "2023-12-31T23:59:59") AS count_yearly_reviews FROM hotel h WHERE h.country = "France";
SELECT b.booking_id, (SELECT SUM(bt.total_price) FROM bookings bt WHERE bt.hotel_id = b.hotel_id AND bt.payment_status = "Paid") AS revenue FROM bookings b WHERE b.checkin <= "2023-11-01T23:59:59";
SELECT h.name, (SELECT AVG(b.total_price) FROM bookings b WHERE b.hotel_id = h.hotel_id AND b.payment_method = "PayPal") AS avg_paypal_income FROM hotel h WHERE h.city = "Los Angeles";
SELECT u.name, (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.user_id = u.user_id) AS booking_count FROM users u WHERE u.city = "London";
SELECT h.name, (SELECT COUNT(r.review_id) FROM reviews r WHERE r.hotel_id = h.hotel_id AND r.ratings.Cleanliness = 5) AS top_cleanliness_reviews FROM hotel h WHERE h.rating > 4;
SELECT b.booking_id, (SELECT MIN(rt.price) FROM hotel h UNNEST h.room_types rt WHERE h.hotel_id = b.hotel_id) AS min_room_price FROM bookings b WHERE b.room_count > 1;
SELECT h.name, (SELECT COUNT(rt.name) FROM h.room_types rt) AS total_room_types FROM hotel h WHERE (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.hotel_id = h.hotel_id) > 100;
SELECT b.booking_id, (SELECT COUNT(r.review_id) FROM reviews r WHERE r.hotel_id = b.hotel_id AND r.ratings.Rooms = 4) AS rooms_rating_four FROM bookings b WHERE b.checkout >= "2023-06-01T00:00:00";
SELECT h.name, (SELECT SUM(rt.availability) FROM h.room_types rt) AS total_availability FROM hotel h WHERE h.city = "Berlin";
SELECT r.review_id, (SELECT AVG(b.total_price) FROM bookings b WHERE b.user_id = r.user_id) AS user_avg_spending FROM reviews r WHERE r.ratings.Cleanliness >= 4;
SELECT b.booking_id, (SELECT h.amenities FROM hotel h WHERE h.hotel_id = b.hotel_id) AS hotel_amenities FROM bookings b WHERE (SELECT COUNT(r.review_id) FROM reviews r WHERE r.hotel_id = b.hotel_id) < 50;
SELECT h.name, (SELECT MAX(r.review_date) FROM reviews r WHERE r.hotel_id = h.hotel_id) AS latest_review_date FROM hotel h WHERE h.free_wifi = FALSE;
SELECT r.review_id, (SELECT h.city FROM hotel h WHERE h.hotel_id = r.hotel_id) AS hotel_city FROM reviews r WHERE r.ratings.Overall = 5;
SELECT b.booking_id, (SELECT COUNT(bt.booking_id) FROM bookings bt WHERE bt.user_id = b.user_id) AS user_contract_count FROM bookings b WHERE b.total_price > 1000;
SELECT h.name, (SELECT MIN(rt.availability) FROM h.room_types rt) AS min_room_availability FROM hotel h WHERE h.rating >= 3;
SELECT h.name, (SELECT COUNT(booking_id) FROM bookings WHERE hotel_id = h.hotel_id AND payment_status = "Pending") AS pending_bookings FROM hotel h WHERE h.country = "Japan";
SELECT r.review_id, (SELECT u.zipcode FROM users u WHERE u.user_id = r.user_id) AS reviewer_zipcode FROM reviews r WHERE r.ratings.Overall < 3;
SELECT b.booking_id, (SELECT h.geo FROM hotel h WHERE h.hotel_id = b.hotel_id) AS hotel_geolocation FROM bookings b WHERE b.payment_status = "Confirmed";
SELECT u.username, (SELECT COUNT(r.comment) FROM reviews r WHERE r.user_id = u.user_id) AS comment_count FROM users u WHERE u.username LIKE "john%";
SELECT h.name, (SELECT SUM(bt.total_price) FROM bookings bt WHERE bt.hotel_id = h.hotel_id) AS total_revenue FROM hotel h WHERE h.type = "Hostel";
SELECT b.booking_id, (SELECT COUNT(*) FROM reviews r WHERE r.hotel_id = b.hotel_id) AS total_hotel_reviews FROM bookings b WHERE (SELECT COUNT(*) FROM reviews r WHERE r.user_id = b.user_id) > 2;
SELECT u.name, (SELECT COUNT(b2.booking_id) FROM bookings b2 WHERE b2.user_id = u.user_id) AS user_booking_count FROM users u WHERE EXISTS (SELECT b.booking_id FROM bookings b WHERE b.user_id = u.user_id AND b.total_price > 150);
SELECT h.name, (SELECT COUNT(r2.review_id) FROM reviews r2 WHERE r2.hotel_id = h.hotel_id) AS hotel_review_count FROM hotel h WHERE h.free_parking = TRUE;
SELECT b.booking_id, (SELECT COUNT(b2.booking_id) FROM bookings b2 WHERE b2.hotel_id = b.hotel_id AND b2.payment_status = "Refunded") AS refunded_count FROM bookings b WHERE b.checkin >= "2023-08-01T00:00:00";
SELECT h.name, (SELECT MAX(rt.price) FROM h.room_types rt) AS max_room_price FROM hotel h WHERE (SELECT AVG(r.ratings.Overall) FROM reviews r WHERE r.hotel_id = h.hotel_id) > 4.5;
SELECT b.booking_id, (SELECT COUNT(rt.name) FROM hotel h UNNEST h.room_types rt WHERE h.hotel_id = b.hotel_id AND rt.availability > 0) AS available_rooms_for_booking FROM bookings b WHERE b.checkin IS NOT NULL;
SELECT h.name, (SELECT AVG(r.ratings.Rooms) FROM reviews r WHERE r.hotel_id = h.hotel_id) AS avg_room_rating FROM hotel h WHERE h.city = "Miami";
SELECT r.review_id, (SELECT b.payment_method FROM bookings b WHERE b.booking_id = r.booking_id AND b.user_id = r.user_id) AS payment_option FROM reviews r WHERE r.ratings.Cleanliness < 4;
SELECT h.name, (SELECT AVG(rt.availability) FROM h.room_types rt) AS avg_availability FROM hotel h WHERE h.type = "Boutique";
SELECT b.booking_id, (SELECT SUM(bt.room_count) FROM bookings bt WHERE bt.user_id = b.user_id) AS total_rooms_booked_by_user FROM bookings b WHERE b.payment_method = "Cash";
SELECT u.username, (SELECT COUNT(ht.name) FROM hotel ht WHERE ht.country = u.country) AS hotels_in_user_country FROM users u WHERE u.city = "Manchester";
SELECT h.name, (SELECT SUM(bt.total_price) FROM bookings bt WHERE bt.hotel_id = h.hotel_id AND bt.payment_status = "Completed") AS completed_revenue FROM hotel h WHERE h.country = "Spain";
SELECT r.review_id, (SELECT SUM(rt.price) FROM hotel h UNNEST h.room_types rt WHERE h.hotel_id = r.hotel_id) AS total_room_type_prices FROM reviews r WHERE r.ratings.Overall >= 4;
SELECT b.booking_id, (SELECT AVG(b2.total_price) FROM bookings b2 WHERE b2.hotel_id = b.hotel_id AND b2.payment_status = "Paid") AS avg_payment FROM bookings b WHERE b.checkin IS NOT NULL;
SELECT b.booking_id, (SELECT h.country FROM hotel h WHERE h.hotel_id = b.hotel_id) AS hotel_country FROM bookings b WHERE b.payment_status = "Failed";
SELECT h.name, (SELECT MIN(rt.availability) FROM h.room_types rt) AS min_avail FROM hotel h WHERE h.free_wifi = TRUE;
SELECT r.review_id, (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.user_id = r.user_id AND b.payment_status = "Paid") AS total_paid_booking_for_user FROM reviews r WHERE r.ratings.Overall > 2;
SELECT b.booking_id, (SELECT COUNT(bt.booking_id) FROM bookings bt WHERE bt.hotel_id = b.hotel_id AND bt.payment_method = "Cash") AS cash_bookings FROM bookings b WHERE b.payment_status = "Refunded";
SELECT r.review_id, (SELECT u.email FROM users u WHERE u.user_id = r.user_id) AS reviewer_email FROM reviews r WHERE r.ratings.`Value` > (SELECT AVG(r2.ratings.`Value`) FROM reviews r2);
SELECT r.review_id, (SELECT u.country FROM users u WHERE u.user_id = r.user_id) AS reviewer_country FROM reviews r WHERE r.ratings.`Check in / front desk` < 3;
SELECT r.review_id, (SELECT u.name FROM users u WHERE u.user_id = r.user_id) AS name_of_user FROM reviews r WHERE r.`ratings`.`Value` > 4;
SELECT h.name, (SELECT MIN(r2.review_date) FROM reviews r2 WHERE r2.hotel_id = h.hotel_id) AS first_review_date FROM hotel h WHERE ANY v IN h.amenities SATISFIES v = "Gym" END;
SELECT r.review_id, (SELECT COUNT(*) FROM bookings b WHERE b.user_id = r.user_id AND b.hotel_id = r.hotel_id) AS booking_count_for_review FROM reviews r WHERE r.comments LIKE "%excellent%";
SELECT h.name, (SELECT COUNT(b2.booking_id) FROM bookings b2 WHERE b2.hotel_id = h.hotel_id) AS total_bookings FROM hotel h WHERE ANY v IN h.amenities SATISFIES v = "Spa" END;
SELECT r.review_id, (SELECT MIN(b.total_price) FROM bookings b WHERE b.user_id = r.user_id AND b.hotel_id = r.hotel_id) AS min_price_spent FROM reviews r WHERE r.ratings.`Value` > 3;
SELECT h.name, (SELECT SUM(r2.ratings.Cleanliness) FROM reviews r2 WHERE r2.hotel_id = h.hotel_id) AS cleanliness_sum FROM hotel h WHERE ANY v IN h.amenities SATISFIES v = "Beach" END;
SELECT r.review_id, (SELECT AVG(bt.room_count) FROM bookings bt WHERE bt.hotel_id = r.hotel_id) AS avg_room_count FROM reviews r WHERE r.ratings.`Check in / front desk` > 3;
