SELECT h.hotel_id, h.name, (SELECT AVG(r.ratings.Overall) FROM reviews r WHERE r.hotel_id = h.hotel_id) AS avg_rating FROM hotel h WHERE h.reviews > (SELECT COUNT(*) FROM reviews r WHERE r.hotel_id = h.hotel_id);
SELECT b.booking_id, b.checkout, (SELECT u.name FROM users u WHERE u.user_id = b.user_id) AS user_name FROM bookings b WHERE EXISTS (SELECT 1 FROM hotel h WHERE h.hotel_id = b.hotel_id AND h.rating > 4);
SELECT h.hotel_id, h.name, (SELECT COUNT(*) FROM bookings b WHERE b.hotel_id = h.hotel_id) AS booking_count FROM hotel h WHERE (SELECT COUNT(*) FROM bookings b WHERE b.hotel_id = h.hotel_id) > 10;
SELECT r.review_id, r.review_date, (SELECT h.name FROM hotel h WHERE h.hotel_id = r.hotel_id) AS hotel_name FROM reviews r WHERE r.ratings.Overall = (SELECT MAX(sub_r.ratings.Overall) FROM reviews sub_r WHERE sub_r.hotel_id = r.hotel_id);
SELECT b.booking_id, b.user_id, (SELECT u.name FROM users u WHERE u.user_id = b.user_id) AS user_name FROM bookings b WHERE b.hotel_id IN (SELECT h.hotel_id FROM hotel h WHERE h.reviews > 500);
SELECT r.review_id, r.user_id, (SELECT h.name FROM hotel h WHERE h.hotel_id = r.hotel_id) AS hotel_name FROM reviews r WHERE r.ratings.Cleanliness = (SELECT MIN(sub_r.ratings.Cleanliness) FROM reviews sub_r WHERE sub_r.user_id = r.user_id);
SELECT h.hotel_id, h.name, (SELECT SUM(b.total_price) FROM bookings b WHERE b.hotel_id = h.hotel_id) AS total_revenue FROM hotel h WHERE h.has_rewards_program = TRUE;
SELECT r.review_id, r.comments, (SELECT u.name FROM users u WHERE u.user_id = r.user_id) AS reviewer_name FROM reviews r WHERE r.hotel_id = (SELECT b.hotel_id FROM bookings b WHERE b.user_id = r.user_id LIMIT 1);
SELECT h.hotel_id, h.name, (SELECT COUNT(*) FROM reviews r WHERE r.hotel_id = h.hotel_id AND r.ratings.Overall = 5) AS five_star_reviews FROM hotel h WHERE h.city IN (SELECT DISTINCT u.city FROM users u WHERE EXISTS (SELECT 1 FROM reviews r WHERE r.user_id = u.user_id AND r.ratings.Overall = 5));
SELECT h.hotel_id, h.name, (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.hotel_id = h.hotel_id AND b.payment_status = 'Paid') AS paid_bookings FROM hotel h WHERE EXISTS (SELECT 1 FROM users u WHERE u.country = h.country AND EXISTS (SELECT 1 FROM bookings b WHERE b.user_id = u.user_id AND b.hotel_id = h.hotel_id));
SELECT u.user_id, u.name, (SELECT h.name FROM hotel h WHERE h.city = u.city AND h.type = 'Spa Resort' LIMIT 1) AS spa_resort_in_city FROM users u WHERE u.country = 'United States';
SELECT r.user_id, r.comments, (SELECT COUNT(*) FROM hotel h WHERE h.type = 'Luxury' AND h.city = (SELECT u.city FROM users u WHERE u.user_id = r.user_id)) AS luxury_hotels_in_user_city FROM reviews r WHERE r.ratings.Overall = 5;
SELECT h.hotel_id, (SELECT COUNT(*) FROM bookings b WHERE b.hotel_id = h.hotel_id AND b.payment_method = 'Credit Card') AS credit_card_bookings FROM hotel h WHERE h.rating > (SELECT AVG(sub_h.rating) FROM hotel sub_h);
SELECT b.booking_id, b.hotel_id, (SELECT AVG(r.ratings.Overall) FROM reviews r WHERE r.hotel_id = b.hotel_id) AS avg_hotel_rating FROM bookings b WHERE b.payment_status = 'Paid';
SELECT h.hotel_id, (SELECT COUNT(*) FROM reviews r WHERE r.hotel_id = h.hotel_id AND r.ratings.Cleanliness = 5) AS cleanest_reviews FROM hotel h WHERE h.amenities LIKE '%Free WiFi%';
SELECT u.user_id, (SELECT COUNT(*) FROM bookings b WHERE b.user_id = u.user_id AND b.payment_status = 'Pending') AS pending_bookings FROM users u WHERE EXISTS (SELECT 1 FROM bookings b WHERE b.user_id = u.user_id);
SELECT b.booking_id, (SELECT h.city FROM hotel h WHERE h.hotel_id = b.hotel_id) AS hotel_city FROM bookings b WHERE b.checkin > '2024-01-01T00:00:00Z';
SELECT r.review_id, (SELECT h.type FROM hotel h WHERE h.hotel_id = r.hotel_id) AS hotel_type FROM reviews r WHERE r.comments LIKE '%excellent%';
SELECT u.user_id, (SELECT SUM(b.total_price) FROM bookings b WHERE b.user_id = u.user_id) AS total_spending FROM users u WHERE u.city IN (SELECT DISTINCT h.city FROM hotel h WHERE h.rating > 4);
SELECT h.hotel_id, (SELECT AVG(r.ratings.Overall) FROM reviews r WHERE r.hotel_id = h.hotel_id) AS avg_overall_rating FROM hotel h WHERE h.has_rewards_program = TRUE;
SELECT b.booking_id, (SELECT u.email FROM users u WHERE u.user_id = b.user_id) AS user_email FROM bookings b WHERE b.payment_status = 'Paid';
SELECT h.hotel_id, (SELECT MIN(b.total_price) FROM bookings b WHERE b.hotel_id = h.hotel_id) AS cheapest_booking FROM hotel h WHERE h.rating > 4;
SELECT u.user_id, (SELECT MAX(r.ratings.Overall) FROM reviews r WHERE r.user_id = u.user_id) AS max_review_rating FROM users u WHERE u.country = 'Canada';
SELECT h.hotel_id, (SELECT AVG(rb.total_price) FROM bookings rb WHERE rb.hotel_id = h.hotel_id AND rb.payment_status = 'Paid') AS avg_price_paid FROM hotel h WHERE h.type = 'Beach Resort';
SELECT u.user_id, (SELECT COUNT(*) FROM reviews r WHERE r.user_id = u.user_id AND r.ratings.Overall = 5) AS five_star_reviews FROM users u WHERE EXISTS (SELECT 1 FROM bookings b WHERE b.user_id = u.user_id AND b.payment_status = 'Cancelled');
SELECT b.booking_id, (SELECT h.type FROM hotel h WHERE h.hotel_id = b.hotel_id) AS hotel_type FROM bookings b WHERE b.total_price > 1000;
SELECT h.hotel_id, (SELECT SUM(r.ratings.Cleanliness) FROM reviews r WHERE r.hotel_id = h.hotel_id) AS total_cleanliness_score FROM hotel h WHERE h.amenities LIKE '%Gym%';
SELECT r.review_id, (SELECT u.username FROM users u WHERE u.user_id = r.user_id) AS username FROM reviews r WHERE r.comments LIKE '%recommend%';
SELECT h.hotel_id, (SELECT COUNT(*) FROM bookings b WHERE b.hotel_id = h.hotel_id AND b.checkin > '2024-06-01T00:00:00Z') AS upcoming_bookings FROM hotel h WHERE h.reviews > 300;
SELECT b.booking_id, (SELECT h.country FROM hotel h WHERE h.hotel_id = b.hotel_id) AS hotel_country FROM bookings b WHERE b.payment_method = 'PayPal';
SELECT u.user_id, (SELECT AVG(r.ratings.Overall) FROM reviews r WHERE r.user_id = u.user_id) AS avg_user_rating FROM users u WHERE EXISTS (SELECT 1 FROM bookings b WHERE b.user_id = u.user_id);
SELECT h.hotel_id, (SELECT COUNT(*) FROM reviews r WHERE r.hotel_id = h.hotel_id) AS review_count FROM hotel h WHERE h.city = 'New York';
SELECT r.review_id, (SELECT h.amenities FROM hotel h WHERE h.hotel_id = r.hotel_id) AS hotel_amenities FROM reviews r WHERE r.ratings.Rooms = 5;
SELECT b.booking_id, (SELECT u.phone FROM users u WHERE u.user_id = b.user_id) AS user_phone FROM bookings b WHERE b.payment_status = 'Pending';
SELECT h.hotel_id, (SELECT COUNT(*) FROM bookings b WHERE b.hotel_id = h.hotel_id) AS total_bookings FROM hotel h WHERE h.rooms > 100;
SELECT u.user_id, (SELECT SUM(b.total_price) FROM bookings b WHERE b.user_id = u.user_id AND b.checkin > '2024-01-01T00:00:00Z') AS future_bookings_spending FROM users u WHERE EXISTS (SELECT 1 FROM reviews r WHERE r.user_id = u.user_id);
SELECT r.review_id, (SELECT COUNT(*) FROM bookings b WHERE b.hotel_id = r.hotel_id) AS total_bookings_for_hotel FROM reviews r WHERE r.ratings.Cleanliness = 5;
SELECT b.booking_id, (SELECT h.email FROM hotel h WHERE h.hotel_id = b.hotel_id) AS hotel_email FROM bookings b WHERE b.payment_method = 'Cash';
SELECT h.hotel_id, (SELECT COUNT(*) FROM reviews r WHERE r.hotel_id = h.hotel_id AND r.ratings.Check_in = 5) AS checkin_rating_5_count FROM hotel h WHERE h.amenities LIKE '%Pool%';
SELECT b.booking_id, (SELECT h.rating FROM hotel h WHERE h.hotel_id = b.hotel_id) AS hotel_ratings FROM bookings b WHERE b.room_count = 2;
SELECT u.user_id, (SELECT h.name FROM hotel h WHERE h.city = u.city LIMIT 1) AS first_hotel_in_city FROM users u WHERE u.zipcode = '90210';
SELECT h.hotel_id, (SELECT MIN(rb.total_price) FROM bookings rb WHERE rb.hotel_id = h.hotel_id AND rb.payment_status = 'Pending') AS min_pending_booking_price FROM hotel h WHERE h.rating > 4.5;
SELECT b.booking_id, (SELECT u.city FROM users u WHERE u.user_id = b.user_id) AS user_city FROM bookings b WHERE b.total_price > (SELECT AVG(rb.total_price) FROM bookings rb);
SELECT r.review_id, (SELECT u.email FROM users u WHERE u.user_id = r.user_id) AS reviewer_email FROM reviews r WHERE r.ratings.Overall = 5;
SELECT h.hotel_id, (SELECT AVG(r.ratings.Rooms) FROM reviews r WHERE r.hotel_id = h.hotel_id) AS avg_room_rating FROM hotel h WHERE h.city = 'Berlin';
SELECT u.user_id, (SELECT MIN(b.checkin) FROM bookings b WHERE b.user_id = u.user_id) AS earliest_checkin FROM users u WHERE EXISTS (SELECT 1 FROM reviews r WHERE r.user_id = u.user_id);
SELECT b.booking_id, (SELECT COUNT(*) FROM reviews r WHERE r.hotel_id = b.hotel_id) AS review_count_for_booking FROM bookings b WHERE b.payment_status = 'Paid';
SELECT h.hotel_id, (SELECT MAX(rb.checkin) FROM bookings rb WHERE rb.hotel_id = h.hotel_id) AS latest_checkin FROM hotel h WHERE h.type = 'Hostel';
SELECT u.user_id, (SELECT COUNT(r.review_id) FROM reviews r WHERE r.user_id = u.user_id AND r.ratings.Overall > 3) AS positive_reviews FROM users u WHERE EXISTS (SELECT 1 FROM bookings b WHERE b.user_id = u.user_id);
SELECT b.booking_id, (SELECT h.phone FROM hotel h WHERE h.hotel_id = b.hotel_id) AS hotel_phone FROM bookings b WHERE b.payment_method = 'Credit Card';
SELECT r.review_id, (SELECT h.url FROM hotel h WHERE h.hotel_id = r.hotel_id) AS hotel_url FROM reviews r WHERE r.ratings.Check_in = 5;
SELECT b.booking_id, (SELECT COUNT(r.review_id) FROM reviews r WHERE r.hotel_id = b.hotel_id) AS total_reviews_for_hotel FROM bookings b WHERE b.payment_status = 'Cancelled';
SELECT h.hotel_id, (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.hotel_id = h.hotel_id) AS booking_count FROM hotel h WHERE h.room_types[0].price < 100;
SELECT u.user_id, (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.user_id = u.user_id AND b.room_type = 'Deluxe') AS deluxe_bookings_count FROM users u WHERE u.country = 'Germany';
SELECT r.review_id, (SELECT h.type FROM hotel h WHERE h.hotel_id = r.hotel_id) AS hotel_type FROM reviews r WHERE r.comments LIKE '%service%';
SELECT h.hotel_id, (SELECT AVG(b.room_count) FROM bookings b WHERE b.hotel_id = h.hotel_id) AS avg_room_count FROM hotel h WHERE h.type = 'Historic';
SELECT b.booking_id, (SELECT h.geo.lat FROM hotel h WHERE h.hotel_id = b.hotel_id) AS hotel_latitude FROM bookings b WHERE b.payment_status = 'Pending';
SELECT u.user_id, (SELECT COUNT(r.review_id) FROM reviews r WHERE r.user_id = u.user_id) AS user_review_count FROM users u WHERE u.city = 'London';
SELECT h.hotel_id, (SELECT MIN(r.ratings.Overall) FROM reviews r WHERE r.hotel_id = h.hotel_id) AS min_overall_rating FROM hotel h WHERE h.country = 'France';
SELECT b.booking_id, (SELECT u.name FROM users u WHERE u.user_id = b.user_id) AS user_name FROM bookings b WHERE b.room_count > 1;
SELECT r.review_id, (SELECT h.email FROM hotel h WHERE h.hotel_id = r.hotel_id) AS hotel_email FROM reviews r WHERE r.ratings.Cleanliness = 5;
SELECT b.booking_id, (SELECT u.name FROM users u WHERE u.user_id = b.user_id) AS user_name FROM bookings b WHERE b.room_count > 1;
SELECT h.hotel_id, (SELECT COUNT(*) FROM reviews r WHERE r.hotel_id = h.hotel_id AND r.ratings.Overall > 4) AS positive_reviews FROM hotel h WHERE h.type = 'Eco Lodge';
SELECT u.user_id, (SELECT AVG(b.total_price) FROM bookings b WHERE b.user_id = u.user_id) AS avg_spending FROM users u WHERE EXISTS (SELECT 1 FROM reviews r WHERE r.user_id = u.user_id);
SELECT r.review_id, (SELECT COUNT(*) FROM hotel h WHERE h.geo.lat = (SELECT u.latitude FROM users u WHERE u.user_id = r.user_id) AND h.geo.long = (SELECT u.longitude FROM users u WHERE u.user_id = r.user_id)) AS nearby_hotels_count FROM reviews r WHERE r.ratings.Overall = 5;
SELECT h.hotel_id, (SELECT SUM(b.total_price) FROM bookings b WHERE b.hotel_id = h.hotel_id) AS total_revenue FROM hotel h WHERE h.type = 'Lodge';
SELECT b.booking_id, (SELECT h.name FROM hotel h WHERE h.hotel_id = b.hotel_id) AS hotel_name FROM bookings b WHERE b.payment_method = 'Credit Card';
SELECT r.review_id, (SELECT h.name FROM hotel h WHERE h.hotel_id = r.hotel_id) AS hotel_name FROM reviews r WHERE r.ratings.Check_in = 5;
SELECT h.hotel_id, (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.hotel_id = h.hotel_id AND b.payment_status = 'Cancelled') AS cancelled_bookings FROM hotel h WHERE h.country = 'Mexico';
SELECT b.booking_id, (SELECT h.name FROM hotel h WHERE h.hotel_id = b.hotel_id) AS hotel_name FROM bookings b WHERE b.payment_status = 'Pending';
SELECT u.user_id, (SELECT AVG(r.ratings.Cleanliness) FROM reviews r WHERE r.user_id = u.user_id) AS avg_cleanliness_rating FROM users u WHERE EXISTS (SELECT 1 FROM bookings b WHERE b.user_id = u.user_id);
SELECT r.review_id, (SELECT AVG(h.rating) FROM hotel h WHERE h.hotel_id = r.hotel_id) AS avg_hotel_rating FROM reviews r WHERE r.ratings.Overall = 5;
SELECT b.booking_id, (SELECT h.amenities FROM hotel h WHERE h.hotel_id = b.hotel_id) AS hotel_amenities FROM bookings b WHERE b.payment_status = 'Cancelled';
SELECT u.user_id, (SELECT MIN(b.total_price) FROM bookings b WHERE b.user_id = u.user_id) AS min_spending FROM users u WHERE EXISTS (SELECT 1 FROM reviews r WHERE r.user_id = u.user_id);
SELECT h.hotel_id, (SELECT COUNT(*) FROM reviews r WHERE r.hotel_id = h.hotel_id AND r.ratings.Rooms = 5) AS top_room_ratings FROM hotel h WHERE h.city = 'Boston';
SELECT b.booking_id, (SELECT h.name FROM hotel h WHERE h.hotel_id = b.hotel_id) AS hotel_name FROM bookings b WHERE b.room_count = 3;
SELECT u.user_id, (SELECT SUM(b.total_price) FROM bookings b WHERE b.user_id = u.user_id AND b.room_count = 1) AS total_spending_on_single_rooms FROM users u WHERE u.city = 'Los Angeles';
SELECT r.review_id, (SELECT h.rating FROM hotel h WHERE h.hotel_id = r.hotel_id) AS hotel_rating FROM reviews r WHERE r.ratings.Overall = 5;
SELECT h.hotel_id, (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.hotel_id = h.hotel_id) AS total_bookings FROM hotel h WHERE h.rooms < 50;
SELECT h.`hotel_id`, h.`name`, (SELECT MAX(r.`ratings`.`Rooms`) FROM `reviews` r WHERE r.`hotel_id` = h.`hotel_id`) AS `best_room_rating` FROM `hotel` h WHERE h.`type` IN ['Luxury', 'Resort'];
SELECT h.hotel_id, (SELECT COUNT(*) FROM reviews r WHERE r.hotel_id = h.hotel_id AND r.ratings.`Value` > 3) AS positive_reviews FROM hotel h WHERE h.has_rewards_program = TRUE;
SELECT r.review_id, (SELECT h.name FROM hotel h WHERE h.hotel_id = r.hotel_id) AS hotel_name FROM reviews r WHERE r.ratings.`Value` = 5;
SELECT u.user_id, (SELECT COUNT(r.review_id) FROM reviews r WHERE r.user_id = u.user_id AND r.ratings.`Value` = 5) AS top_value_reviews FROM users u WHERE EXISTS (SELECT 1 FROM bookings b WHERE b.user_id = u.user_id);
SELECT h.`hotel_id`, (SELECT RAW COUNT(*) FROM `reviews` AS r WHERE r.`hotel_id` = h.`hotel_id` AND r.`ratings`.`Overall` > 3) AS `positive_reviews` FROM `hotel` AS h WHERE h.`type` IN ["Lodge", "Eco Lodge"];
SELECT r.review_id, (SELECT COUNT(h.hotel_id) FROM hotel h WHERE h.country = (SELECT u.country FROM users u WHERE u.user_id = r.user_id)) AS num_hotels_in_user_country FROM reviews r WHERE r.ratings.`Value` = 4;