SELECT b.hotel_id, (SELECT COUNT(booking_id) FROM bookings WHERE payment_status = 'Paid' GROUP BY hotel_id HAVING COUNT(booking_id) > 5) AS paid_bookings FROM bookings b WHERE b.payment_status = 'Paid' GROUP BY b.hotel_id;
SELECT b.user_id, COUNT(b.booking_id) AS booking_count FROM bookings b WHERE b.payment_status = 'Refunded' GROUP BY b.user_id;
SELECT r.hotel_id, AVG(r.ratings.Cleanliness) AS avg_cleanliness_rating, COUNT(r.review_id) AS num_reviews FROM hotel h JOIN reviews r ON r.hotel_id = h.hotel_id WHERE h.rating > 3 GROUP BY r.hotel_id;
SELECT h.city, COUNT(*) AS num_hotels, AVG(h.rating) AS avg_city_rating FROM hotel h WHERE h.free_parking = TRUE GROUP BY h.city;
SELECT h.hotel_id, (SELECT COUNT(*) FROM `reviews` AS r WHERE r.hotel_id = h.hotel_id AND r.ratings.Overall > 4) AS high_rating_reviews, (SELECT COUNT(*) FROM `bookings` AS b WHERE b.hotel_id = h.hotel_id) AS total_bookings FROM `hotel` AS h WHERE h.rating > 3;
SELECT h.hotel_id, MAX(rt.price) AS max_room_price FROM hotel h UNNEST h.room_types AS rt WHERE h.city = 'Los Angeles' GROUP BY h.hotel_id;
SELECT r.hotel_id AS review_hotel_id, AVG(r.ratings.Rooms) AS avg_room_rating FROM reviews AS r WHERE r.ratings.Rooms > 3 GROUP BY r.hotel_id;
SELECT b.user_id, AVG(b.room_count) AS avg_rooms_booked FROM bookings b WHERE b.room_count > 1 GROUP BY b.user_id;
SELECT h.country AS hotel_country, COUNT(h.hotel_id) AS num_hotels FROM hotel h WHERE h.free_parking = TRUE GROUP BY h.country;
SELECT h.type, AVG(h.rating) AS avg_type_rating FROM hotel h WHERE h.rating > 3 GROUP BY h.type;
SELECT b.user_id, MIN(b.checkin) AS first_checkin FROM bookings b WHERE b.payment_status = 'Paid' GROUP BY b.user_id;
SELECT r.user_id, COUNT(r.review_id) AS perfect_reviews FROM reviews r WHERE r.ratings.Overall = 5 GROUP BY r.user_id;
SELECT h.city, MIN(rt.availability) AS min_availability FROM hotel h UNNEST h.room_types AS rt WHERE h.free_parking = TRUE GROUP BY h.city;
SELECT b.payment_method, AVG(b.total_price) AS avg_payment_price FROM bookings b WHERE b.total_price > 100 GROUP BY b.payment_method;
SELECT r.hotel_id, COUNT(DISTINCT r.user_id) AS num_reviewers FROM reviews r WHERE r.ratings.Overall > 3 GROUP BY r.hotel_id;
SELECT h.city, MAX(h.rating) AS top_hotel_rating FROM hotel h WHERE h.rating > 4 GROUP BY h.city;
SELECT r.user_id, AVG(r.ratings.Rooms) AS avg_room_rating FROM users u JOIN reviews r ON r.user_id = u.user_id WHERE u.city = 'Boston' GROUP BY r.user_id;
SELECT h.country AS hotel_loc, COUNT(h.hotel_id) AS num_hotels FROM hotel h WHERE h.free_wifi = FALSE GROUP BY h.country;
SELECT b.user_id, SUM(b.total_price) AS total_spent FROM bookings b WHERE b.payment_status = 'Paid' GROUP BY b.user_id;
SELECT h.hotel_id, (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.hotel_id = h.hotel_id AND b.payment_status = 'Pending') AS pending_bookings FROM hotel h;
SELECT u.country, AVG((SELECT RAW AVG(total_price) FROM bookings WHERE user_id = u.user_id)[-1]) AS avg_user_spend FROM users u GROUP BY u.country;
SELECT b.hotel_id, AVG(b.total_price) AS avg_credit_card_price FROM bookings b WHERE b.payment_method = 'Credit Card' GROUP BY b.hotel_id;
SELECT h.name, AVG(rt.price) AS avg_room_price FROM hotel h UNNEST h.room_types AS rt WHERE 'Pool' IN h.amenities GROUP BY h.name;
SELECT b.payment_method, AVG(b.room_count) AS avg_rooms_per_booking FROM bookings b GROUP BY b.payment_method;
SELECT u.username, MIN((SELECT MIN(b.checkout) FROM bookings b WHERE b.user_id = u.user_id)) AS earliest_checkout FROM users u GROUP BY u.username;
SELECT u.user_id, COUNT(r.review_id) AS number_of_reviews FROM users u LEFT JOIN reviews r ON u.user_id = r.user_id WHERE u.country = 'USA' GROUP BY u.user_id;
SELECT h.hotel_id, AVG(rt.price) AS avg_room_type_price FROM hotel h UNNEST h.room_types AS rt WHERE h.city = 'Seattle' GROUP BY h.hotel_id;
SELECT h.name, (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.hotel_id = h.hotel_id) AS total_bookings FROM hotel h WHERE h.city = 'Orlando';
SELECT b.user_id, MIN(b.total_price) AS min_spending FROM users u JOIN bookings b ON b.user_id = u.user_id WHERE u.city = 'Houston' GROUP BY b.user_id;
SELECT h.geo.lat, h.geo.long, MAX(rt.price) AS most_expensive_room FROM hotel h UNNEST h.room_types AS rt WHERE h.rating > 4 GROUP BY h.geo.lat, h.geo.long;
SELECT r.hotel_id, COUNT(DISTINCT r.user_id) AS unique_reviewers FROM reviews r WHERE r.ratings.Cleanliness > 3 GROUP BY r.hotel_id;
SELECT h.amenities, AVG(rt.price) AS avg_room_price FROM hotel h UNNEST h.room_types AS rt WHERE h.rooms > 100 GROUP BY h.amenities;
SELECT h.name AS hotel_name, COUNT(b.booking_id) AS bookings_count FROM hotel h LEFT JOIN bookings b ON b.hotel_id = h.hotel_id WHERE h.rating > 3 GROUP BY h.name;
SELECT u.user_id, (SELECT COUNT(r.review_id) FROM reviews r WHERE r.user_id = u.user_id) AS total_reviews_made FROM users u WHERE u.zipcode = '90001';
SELECT b.room_type, AVG(b.total_price) AS avg_cost_per_room FROM bookings b WHERE b.total_price > 500 GROUP BY b.room_type;
SELECT h.type, COUNT(h.hotel_id) AS total_type FROM hotel h WHERE h.free_parking = TRUE GROUP BY h.type;
SELECT r.review_id, (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.user_id = r.user_id) AS num_bookings FROM reviews r;
SELECT u.country, MAX((SELECT bk.total_price FROM bookings bk WHERE bk.user_id = u.user_id)) AS max_spend FROM users u GROUP BY u.country;
SELECT h.hotel_id, AVG(rt.availability) AS avg_availability FROM hotel h UNNEST h.room_types AS rt WHERE h.city = 'San Jose' GROUP BY h.hotel_id;
SELECT r.review_id, COUNT(*) AS total_reviews FROM reviews r GROUP BY r.review_id;
SELECT b.user_id, MIN(b.checkin) AS first_checkin FROM users u JOIN bookings b ON b.user_id = u.user_id WHERE u.country = 'France' GROUP BY b.user_id;
SELECT u.user_id, MAX(r.ratings.Cleanliness) AS highest_cleanliness_rating FROM users u JOIN reviews r ON r.user_id = u.user_id WHERE u.country = 'Spain' GROUP BY u.user_id;
SELECT h.city, AVG(rt.price) AS avg_room_rate FROM hotel h UNNEST h.room_types AS rt WHERE h.free_wifi = FALSE GROUP BY h.city;
SELECT b.payment_method, COUNT(*) AS canceled_count FROM bookings b WHERE b.payment_status = 'Canceled' GROUP BY b.payment_method;
SELECT u.country, COUNT(u.user_id) AS user_count FROM `users` u WHERE u.country IN ["Italy", "Germany"] GROUP BY u.country;
SELECT h.hotel_id, MAX(rt.price) AS max_room_price FROM hotel h UNNEST h.room_types AS rt WHERE h.country = 'Brazil' GROUP BY h.hotel_id;
SELECT r.user_id, SUM(r.ratings.Rooms) AS rooms_total_score FROM reviews r WHERE r.ratings.Rooms > 3 GROUP BY r.user_id;
SELECT h.name, (SELECT COUNT(b.booking_id) FROM bookings b WHERE b.hotel_id = h.hotel_id) AS total_bookings FROM hotel h WHERE h.type = 'Motel';
SELECT h.city, COUNT(h.hotel_id) AS city_hotel_count FROM hotel h WHERE h.rating >= 4 GROUP BY h.city;
SELECT r.hotel_id, MIN(r.review_date) AS earliest_review FROM reviews r JOIN hotel h ON r.hotel_id = h.hotel_id WHERE h.country = 'Argentina' GROUP BY r.hotel_id;
SELECT r.room_type, COUNT(r.booking_id) AS bookings_for_type FROM bookings r GROUP BY r.room_type;
