SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP DATABASE IF EXISTS `DATABASE_NAME`;

CREATE SCHEMA IF NOT EXISTS `DATABASE_NAME` DEFAULT CHARACTER SET utf8  COLLATE utf8_bin;

USE `DATABASE_NAME` ;

CREATE TABLE IF NOT EXISTS `DATABASE_NAME`.`simple_table` (
  `primary_key_id` VARCHAR(100) NOT NULL,
  `int_field1` INT(11) NULL DEFAULT NULL,
  `decimal_field1` DECIMAL(10,0) NULL DEFAULT NULL,
  `datetime_field1` DATETIME NULL DEFAULT NULL,
  `bool_field1` TINYINT(1) NULL DEFAULT 0,
  `varchar_field1` VARCHAR(1000) NULL,
  `char_field1` CHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`primary_key_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10007
DEFAULT CHARACTER SET utf8  COLLATE utf8_bin;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
