eventing.eventing_analytics.EventingAnalytics:
    test_analytics_sanity,nodes_init=3,services_init=kv:index:n1ql:cbas-kv:eventing,dataset=default,groups=simple,reset_services=True,use_single_bucket=True,handler_code=analytics_basic_select
eventing.eventing_encryption_at_rest.EventingEncryptionAtRest:
    test_log_encryption_sanity,nodes_init=2,services_init=kv-eventing,dataset=default,groups=simple,reset_services=True,handler_code=logger
    test_log_encryption_dek_continuous_rotation,nodes_init=2,services_init=kv-eventing,dataset=default,groups=simple,reset_services=True,handler_code=logger,dek_rotation_interval=60,num_rotations=5,rotation_wait_timeout=600,GROUP=key_rotation
    test_log_encryption_force_rotate_and_reencrypt,nodes_init=2,services_init=kv-eventing,dataset=default,groups=simple,reset_services=True,handler_code=logger,GROUP=key_rotation
eventing.eventing_jwt_auth.EventingJWTAuth:
    test_eventing_jwt_auth_sanity,nodes_init=2,services_init=kv-eventing,dataset=default,groups=simple,reset_services=True,use_single_bucket=True,jit_provisioning=False,handler_code=bucket_op
    test_expired_jwt_token,nodes_init=2,services_init=kv-eventing,dataset=default,groups=simple,reset_services=True,use_single_bucket=True,jit_provisioning=False,handler_code=bucket_op
eventing.eventing_fts_query_support.EventingFTSQuerySupport:
    test_eventing_fts_query_support_sanity,nodes_init=3,services_init=kv:index:n1ql-fts-kv:eventing,dataset=default,groups=simple,reset_services=True,use_single_bucket=True,handler_code=match_query

