#!/usr/bin/env python

import sys
import unittest
sys.path.append("pytests")
sys.path.append("lib")

from management.version_check import VerifyVersionTest

if __name__ == '__main__':
    suite = unittest.TestLoader().loadTestsFromTestCase(VerifyVersionTest)
    result = unittest.TextTestRunner(verbosity=0).run(suite)
    if result.failures or result.errors:
        sys.exit(-1)
    sys.exit(0)