#!/usr/bin/env python

import sys
import unittest
import os
sys.path.append("lib")
sys.path.append("pytests")

if __name__ == '__main__':
    import logger
    logger.Logger.start_logger('InstallTest')
    from management.install import InstallTest
    suite = unittest.TestLoader().loadTestsFromTestCase(InstallTest)
    for test in suite:
        from TestInput import TestInputParser
        test.input = TestInputParser.get_test_input(sys.argv)
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    logger.Logger.stop_logger()
    if result.failures or result.errors:
        sys.exit(-1)
    sys.exit(0)
