#!/usr/bin/env python

import sys
import unittest
sys.path.append(".")
sys.path.append("lib")
sys.path.append("pytests")

if __name__ == '__main__':
    import logger
    logger.Logger.start_logger('SimpleSetGetMembaseBucketDefaultPort11211.test_set_get_small_keys')
    suite = unittest.TestLoader().loadTestsFromNames(names =[
    'memcachedops.set_get_test.SimpleSetGetMembaseBucketDefaultPort11211.test_set_get_small_keys'])
    from TestInput import TestInputParser,TestInputSingleton
    TestInputSingleton.input = TestInputParser.get_test_input(sys.argv)
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    logger.Logger.stop_logger()
    if result.failures or result.errors:
        sys.exit(-1)
    sys.exit(0)