gsi.composite_vector_index.CompositeVectorIndex:
    test_composite_vector_sanity,init_nodes=False,nodes_init=3,services_init=kv:n1ql-index-index,default_bucket=False,skip_cleanup=True,skip_load=True,create_primary_index=False,num_of_docs_per_collection=157308,use_magma_loader=True,isSparse=True,json_template=AmazonSparse,vector_backup_filename=backup_zips/Amazon_Reviews_Data.zip,sparsejl_dim=4096,single_distance_function=True

# DCP rebalance
    test_rebalance,init_nodes=False,nodes_init=3,services_init=kv:n1ql-index-index,default_bucket=False,skip_cleanup=True,skip_load=True,create_primary_index=False,use_magma_loader=True,isSparse=True,json_template=MsMARCO,sparsejl_dim=4096,rebalance_type=rebalance_swap

# File based rebalance
gsi.composite_vector_index.CompositeVectorIndex:
    test_rebalance,init_nodes=False,nodes_init=3,services_init=kv:n1ql-index-index,default_bucket=False,skip_cleanup=True,skip_load=True,create_primary_index=False,use_magma_loader=True,isSparse=True,json_template=MsMARCO,sparsejl_dim=4096,rebalance_type=rebalance_swap,shard_based_rebalance=True

# Rollback and recovery
gsi.composite_vector_index.CompositeVectorIndex:
    test_recover_from_disk_snapshot,nodes_init=3,services_init=kv:n1ql-index-index,default_bucket=False,skip_cleanup=True,skip_load=True,create_primary_index=False,use_magma_loader=True,isSparse=True,json_template=MsMARCO,sparsejl_dim=4096

# replica repair
gsi.composite_vector_index.CompositeVectorIndex:
    test_replica_repair,nodes_init=3,services_init=kv:n1ql-index-index,default_bucket=False,skip_cleanup=True,skip_load=True,create_primary_index=False,num_of_docs_per_collection=100000,use_magma_loader=True,isSparse=True,json_template=MsMARCO,sparsejl_dim=4096

# mutations
gsi.composite_vector_index.CompositeVectorIndex:
    test_scans_after_vector_field_mutations,init_nodes=False,nodes_init=3,services_init=kv:n1ql-index-index,default_bucket=False,skip_cleanup=True,skip_load=True,create_primary_index=False,num_of_docs_per_collection=100000,use_magma_loader=True,isSparse=True,json_template=MsMARCO,sparsejl_dim=4096
