fts.stable_topology_fts.StableTopFTS:
    test_deep_pagination_search_after_nontextual,cluster=D,F+Q,F+Q,items=100000,sort_type=numeric,partial_size=2,partial_start_index=3
    test_deep_pagination_full_walk_nontextual,cluster=D,F+Q,F+Q,items=100000,sort_type=geo,page_size=1000
fts.moving_topology_fts.MovingTopFTS:
    swap_rebalance_during_index_building,items=100000,cluster=D,D,F,F,replicas=0

