fts.fts_bq_vector_search.BQVectorSearch:
    test_bq_index_creation,cluster=D,D,F+Q,F+Q,kv=["b1.s1.c1","b1.s1.c2","b1.s1.c3"],dimension=1024,k=100,num_queries=5,index_retry=100,bq_index_type=bivf-sq8,vector_backup_filename=backup_zips/100k_cars_baai_1024.zip,bq_vector_field=descriptionVector
    test_bq_indexing_and_binarisation_verification,cluster=D,D,F+Q,F+Q,kv=["b1.s1.c1","b1.s1.c2","b1.s1.c3"],dimension=1024,k=100,num_queries=5,index_retry=100,bq_index_type=bivf-sq8,vector_backup_filename=backup_zips/100k_cars_baai_1024.zip,bq_vector_field=descriptionVector,GROUP=P0;SET1
fts.fts_vector_search.VectorSearch:
    test_basic_vector_search,cluster=F+Q,F,kv=["b1.s1.c1"],idx=[("i1","b1.s1.c1")],dimension=128,k=100,num_queries=100,index_retry=100,skip_validation_if_no_query_hits=False,rrf=True,fusion_strategy=rrf
fts.fts_fastmerge_vector_search.FastMergeVectorSearch:
    test_fm_index_definition_validation,cluster=F+Q,F,kv=["b1.s1.c1"],dimension=128,k=100,num_queries=3,index_retry=100,vector_dataset=sift
fts.stable_topology_fts.StableTopFTS:
    test_deep_pagination_search_after_nontextual,cluster=D,F+Q,F+Q,items=100000,sort_type=numeric,partial_size=2,partial_start_index=3
    test_deep_pagination_full_walk_nontextual,cluster=D,F+Q,F+Q,items=100000,sort_type=geo,page_size=1000
fts.moving_topology_fts.MovingTopFTS:
    swap_rebalance_during_index_building,items=100000,cluster=D,D,F,F,replicas=0

