#!/usr/bin/env python

import sys
import unittest
sys.path.append(".")
sys.path.append("lib")
sys.path.append("pytests")

if __name__ == '__main__':
    import logger
    logger.Logger.start_logger('test_add_node_already_added_with_bucket')
    suite = unittest.TestLoader().loadTestsFromNames(names =[
    'management.addnodes.addnodestests.AddNodesTests.test_add_node_already_added_with_bucket'])
    from TestInput import TestInputParser,TestInputSingleton
    TestInputSingleton.input = TestInputParser.get_test_input(sys.argv)
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    logger.Logger.stop_logger()
    if result.failures or result.errors:
        sys.exit(-1)
    sys.exit(0)