upgrade.xdcr_upgrade_collections.XDCRUpgradeCollectionsTests:
    test_xdcr_upgrade_with_services,initial_version=8.0.0-3777,nodes_init=4,enable_migration=True,skip_security_scan=True,GROUP=8_0;8_0_0
    test_xdcr_upgrade_with_services,initial_version=8.0.1-4792,nodes_init=4,enable_migration=True,skip_security_scan=True,GROUP=8_0;8_0_1
    test_xdcr_upgrade_with_services,initial_version=8.0.2-5503,nodes_init=4,enable_migration=True,skip_security_scan=True,GROUP=8_0;8_0_2
    test_xdcr_upgrade_with_services,initial_version=8.0.3-5933,nodes_init=4,enable_migration=True,skip_security_scan=True,GROUP=8_0;8_0_3
    # rebalance
    test_xdcr_upgrade_with_services,initial_version=8.0.0-3777,nodes_init=4,after_events=rebalance_out-rebalance_in,dgm_run=True,skip_security_scan=True,GROUP=8_0;8_0_0
    test_xdcr_upgrade_with_services,initial_version=8.0.1-4792,nodes_init=4,after_events=rebalance_out-rebalance_in,dgm_run=True,skip_security_scan=True,GROUP=8_0;8_0_1
    test_xdcr_upgrade_with_services,initial_version=8.0.2-5503,nodes_init=4,after_events=rebalance_out-rebalance_in,dgm_run=True,skip_security_scan=True,GROUP=8_0;8_0_2
    test_xdcr_upgrade_with_services,initial_version=8.0.3-5933,nodes_init=4,after_events=rebalance_out-rebalance_in,dgm_run=True,skip_security_scan=True,GROUP=8_0;8_0_3
