xdcr.targetAwarenessXDCR.TargetAwarenessXDCR:
    test_target_awareness,rdirection="unidirection"
    test_target_awareness,rdirection="bidirection"
    test_heartbeat,rdirection="unidirection"
    test_heartbeat_view_on_all_target_nodes,rdirection="unidirection"
    test_non_kv_node_excluded_from_heartbeat,rdirection="unidirection"
    test_non_kv_node_excluded_from_heartbeat,rdirection="unidirection",orchestrator_on_non_kv=True
    test_rebalance_updates_source_node_list,rdirection="unidirection"
    test_failed_over_node_dropped_from_heartbeat,rdirection="unidirection"
    test_replication_delete,rdirection="unidirection"
    test_node_crash,rdirection="unidirection"
    test_network_failure,rdirection="unidirection"
    # Disabled due to https://jira.issues.couchbase.com/browse/MB-73093, reenable after fix
    # test_failed_over_orchestrator_dropped_from_heartbeat,rdirection="unidirection"
    # test_source_cluster_name_propagation,rdirection="unidirection"
