xdcr.forwardLocalOnlyXDCR.ForwardLocalOnlyXDCRTests:
    # Base 2-cluster bidirectional AA tests
    test_forward_local_only_sdk_create_update,items=100000,sdk_count=100000,replication_drain_timeout=1800,doc_count_sync_timeout=1800,rdirection=bidirection,ctopology=chain,replication_type=xmem,GROUP=P0
    test_forward_local_only_with_advanced_filter,items=100000,sdk_count=100000,filter_settle_timeout=60,replication_drain_timeout=1800,doc_count_sync_timeout=1800,rdirection=bidirection,ctopology=chain,replication_type=xmem,GROUP=P1
xdcr.xdcr_jwt_auth.XDCRJWTAuth:
    test_jwt_admin_full_replication_lifecycle,ctopology=chain,enable_dp=True
xdcr.memoryTestXDCR.MemoryTestXDCR:
    test_boundary_value,dcpFlowControlThrottle=5
xdcr.xdcrDiffer.XDCRDifferTest:
    test_xdcr_differ,rdirection=unidirection,ctopology=chain,encryptionPassphrase=secret,GROUP=P0
xdcr.statsXDCR.StatsXDCR:
    test_xdcr_data_replicated_uncompress,
    test_xdcr_data_replicated_uncompress_backfill
xdcr.filterDelExpXDCR.XDCRFilterDelExpTests:
    test_filter_deletions_and_expirations_together,items=50,ttl=60,rdirection=unidirection,ctopology=chain,replication_type=xmem,default@C1=filter_expression:REGEXP_CONTAINS(META()dotidcomma'^filter'),failure_restart_interval:20,timeout_percentage:60,GROUP=P0