#!/bin/bash
prefix=${prefix}
total_masters=${total_masters}

if [ ${load_phase} -eq 1 ] ; then
    num_clients=3
fi

if [ -n "${hot_load_phase}" ] ; then
    num_clients=1
fi

if(${multi}); then
    node_clients=$[${num_clients}/$total_masters]
    shift=$[$prefix*$node_clients]
    stop_after=$[$shift+$node_clients]
    for (( client=$shift; client<$stop_after; client++ ))
    do
        scripts/perf/client $client ${num_clients} &
    done
    wait
else
    scripts/perf/client ${prefix} ${num_clients}
fi
