#!/bin/bash
prefix=$1
test_id=$2

if [ -z ${num_clients} ]; then
    num_clients=`grep total_clients ${test_conf} | cut -c 13-`
fi

if [ -z "${total_masters}" ]; then
    total_masters=3
fi

echo "prefix:"${prefix}", num_clients="${num_clients}", total_masters="${total_masters}

phase="access"

if [ ${load_phase} -eq 1 ] ; then
    num_clients=3
    phase="load"
fi

if [ -n "${hot_load_phase}" ] ; then
    phase="reload"
fi

if(${multi}); then
    node_clients=$[${num_clients}/$total_masters]
    shift=$[$prefix*$node_clients]
    stop_after=$[$shift+$node_clients]
    for (( client=$shift; client<$stop_after; client++ ))
    do
        scripts/perf/client $client ${num_clients} 2>&1 | tee ${client}-${num_clients}-${phase}.log &
    done
    wait
else
    scripts/perf/client ${prefix} ${num_clients} ${test_id}
fi
