#!/bin/bash
prefix=$1
num_clients=$2
total_masters=$3

echo "prefix:"${prefix}", num_clients="${num_clients}", total_masters="${total_masters}

phase="access"

if [ ${load_phase} -eq 1 ] ; then
    num_clients=3
    phase="load"
fi

if [ -n "${hot_load_phase}" ] ; then
    num_clients=1
    phase="reload"
fi

if(${multi}); then
    node_clients=$[${num_clients}/$total_masters]
    shift=$[$prefix*$node_clients]
    stop_after=$[$shift+$node_clients]
    for (( client=$shift; client<$stop_after; client++ ))
    do
        scripts/perf/client $client ${num_clients} 2>&1 | tee ${client}-${num_clients}-${phase}.log &
    done
    wait
else
    scripts/perf/client ${prefix} ${num_clients}
fi
