#!/bin/sh

git clean -dfx
Rscript resources/R/ep1.R ${baseline_build} ${target_build} ${test_case}.loop 10.5.2.41 eperf ${run_id} ${filename}

if [ -n ${filename} ]; then
  filename=`ls | grep pdf`
  fi

dbname=`echo $filename | cut -d - -f1 | cut -d . -f1`

python -m scripts.perf.graph_poster -n http://10.5.2.41:5984 -d ${dbname} -f ${filename}
