#!/bin/sh

git clean -dfx
cd resources/R/
Rscript ep1.R ${baseline_build} ${target_build} ${test_case}.loop couchdb2.couchbaseqe.com eperf ${run_id} ${filename}

if [ -n ${filename} ]; then
  filename=`ls | grep pdf`
  fi

dbname=`echo $filename | cut -d - -f1`
../../scripts/perf/graph_poster.py -n http://10.5.2.41:5984 -d ${dbname} -f ${filename}
