#!/bin/sh

echo scripts/perf/parent: testing ${product}: ${version_number} num_nodes=${1} -- ${PARENT_BUILD_NUMBER} - ${BUILD_NUMBER}

git rev-parse HEAD
git describe --always --long

echo notes: ${notes}

echo test_conf: ${test_conf}
cat ${test_conf}

echo ini_file: ${ini_file}
cat ${ini_file}

if [ -n ${toy_build} ] ; then
   toy=",toy=${toy_build}"
fi

if [ ${skip_install} != "1" ]; then
   python scripts/install.py -i ${ini_file} -p product=${product},version=${version_number},vbuckets=1024,parallel=True,disable_consistency=1$toy
else
   echo "No Setup"
fi

if [ -z ${test} ] ; then
    test=`grep performance. ${test_conf} | head -n 1`
fi

if [ -z ${mem_quota} ] ; then
    mem_quota=`grep mem_quota ${test_conf} | head -n 1`
fi

if [ ${skip_run} != "1" ]; then
   python pytests/performance/do_cluster.py -i ${ini_file} -c ${test_conf} -p load_phase=0,index_phase=0,access_phase=0,num_nodes=${1},mem_quota=${mem_quota} setUp
else
   echo "No Cluster setup run"
fi