#!/bin/sh

echo testing ${product}: ${version_number}

git rev-parse HEAD
git describe --always --long

echo notes: ${notes}

echo test_conf: ${test_conf}
cat ${test_conf}

echo ini_file: ${ini_file}
cat ${ini_file}

if [ -n ${toy_build} ] ; then
   toy=",toy=${toy_build}"
fi

if [ ${skip_install} != "1" ]; then
   python scripts/install.py -i ${ini_file} -p product=${product},version=${version_number},vbuckets=1024,parallel=True$toy
else
   echo "No Setup"
fi

if [ ${skip_run} != "1" ]; then
   python pytests/performance/do_cluster.py -i ${ini_file} -p test=${test},load_phase=0,index_phase=0,access_phase=0,num_nodes=2,mem_quota=20000 setUp
else
   echo "No Cluster setup run"
fi