#!/bin/sh

# determine number of clients
if [ -z ${1} ]; then
    num_clients=3
else
    num_clients=${1}
fi

# hacky way of aggregating stats from clients
python pytests/performance/do_cluster.py -i ${ini_file} -c ${test_conf} -p num_clients=$num_clients tearDown

# backup
rm -rf backup
mkdir backup
cp final.* backup/
cp *.gz backup/

# decompress all json files
gunzip final.*.json.gz
easy_install couchdbkit

# iterate json file for each phase(load/reload/access),\
# post results to couchdb seperately
FILES=final.*.json
for f in $FILES
do
echo "posting $f to couchdb"
python scripts/post-perf-data.py -n http://couchdb2.couchbaseqe.com:5984 -d eperf -i $f
done
rm -rf final.*.json
rm -rf *.gz
