#!/bin/sh

# determine number of clients
if [ -z ${1} ]; then
    num_clients=3
else
    num_clients=${1}
fi

# install couchdbkit
easy_install couchdbkit  > /dev/null

# hacky way of aggregating stats from clients
python -m pytests.performance.do_cluster -i ${ini_file} -c ${test_conf} -p num_clients=$num_clients tearDown

# iterate json file for each phase (load/reload/access), post results to couchdb seperately
for f in final.*.json
do
    echo "posting $f to couchdb"
    python -m scripts.post_perf_data -n http://10.5.2.41:5984 -d eperf -i $f
done

# Cleanup
rm -rf final.*.json
rm -rf *.gz
